export const movies = [
  {
    title: "Медведь",
    original: ["The Bear"],
    release: "2025-06-25",
    publish: "2025-09-06T19:31:46",
    format: "сериал",
    season: "4",
    isMiniSeries: false,
    liked: "like",
    screenshots: 78,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/4481731/",
  }, // медведь 4
  {
    title: "Голый пистолет",
    original: ["The Naked Gun"],
    release: "2025-08-01",
    publish: "2025-09-06T16:11:52",
    directors: ["Акива Шаффер"],
    format: "фильм",
    liked: "like",
    screenshots: 24,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/817971/",
  }, // голый пистолет (2025)
  {
    title: "Элио",
    original: ["Elio"],
    release: "2025-06-20",
    publish: "2025-08-30T14:54:55",
    directors: ["Эдриан Молина", "Мадлен Шарафьян", "Доми Ши"],
    format: "фильм",
    liked: "dislike",
    screenshots: 54,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/4893253/",
  }, // элио
  {
    title: "Рик и Морти",
    original: ["Rick and Morty"],
    release: "2025-05-25",
    publish: "2025-08-30T11:38:41",
    creators: ["Дэн Хармон", "Джастин Ройланд"],
    format: "сериал",
    season: "8",
    isMiniSeries: false,
    liked: "like",
    screenshots: 36,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/685246/",
  }, // рик и морти 8
  {
    title: "Супермен",
    original: ["Superman"],
    release: "2025-07-11",
    publish: "2025-08-26T07:46:23",
    directors: ["Джеймс Ганн"],
    format: "фильм",
    liked: "like",
    screenshots: 50,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/997647/",
  }, // супермен
  {
    title: "Стерилизован",
    original: ["Fixed"],
    release: "2025-08-13",
    publish: "2025-08-24T07:35:20",
    directors: ["Генндий Тартаковский"],
    format: "фильм",
    liked: "dislike",
    screenshots: 20,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/4695962/",
  }, // стерилизован
  {
    title: "Миссия невыполнима: Финальная расплата",
    original: ["Mission: Impossible - The Final Reckoning"],
    release: "2025-05-23",
    publish: "2025-08-21T20:42:26",
    directors: ["Кристофер Маккуорри"],
    format: "фильм",
    liked: "like",
    screenshots: 33,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1229683/",
  }, // миссия невыполнима: финальная расплата
  {
    title: "Шалом, папик!",
    original: ["Shiva Baby"],
    release: "2021-04-21",
    publish: "2025-08-19T07:11:31",
    directors: ["Эмма Селигман"],
    format: "фильм",
    liked: "like",
    screenshots: 18,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1324912/",
  }, // шалом, папик!
  {
    title: "Прости, детка",
    original: ["Sorry, Baby"],
    release: "2025-07-25",
    publish: "2025-08-17T13:43:40",
    directors: ["Ева Виктор"],
    format: "фильм",
    liked: "like",
    screenshots: 57,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/7092649/",
  }, // прости, детка
  {
    title: "Жизнь Чака",
    original: ["The Life of Chuck"],
    release: "2025-06-13",
    publish: "2025-08-16T16:28:55",
    directors: ["Майк Флэнаган"],
    format: "фильм",
    liked: "dislike",
    screenshots: 27,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5406956/",
  }, // жизнь чака
  {
    title: "Главы государств",
    original: ["Heads of State"],
    release: "2025-07-02",
    publish: "2025-08-16T13:07:36",
    directors: ["Илья Найшуллер"],
    format: "фильм",
    liked: "dislike",
    screenshots: 18,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5278126/",
  }, // главы государств
  {
    title: "Приключения Тинтина: Тайна единорога",
    original: ["The Adventures of Tintin"],
    release: "2011-12-21",
    publish: "2025-08-06T07:41:41",
    directors: ["Стивен Спилберг"],
    format: "фильм",
    liked: "like",
    screenshots: 44,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/406186/",
  }, // приключения тинтина
  {
    title: "Младший брат",
    original: ["Didi", "Dìdi", "弟弟"],
    release: "2024-08-16",
    publish: "2025-08-03T09:52:57",
    directors: ["Шон Ван"],
    format: "фильм",
    liked: "like",
    screenshots: 48,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5448457/",
  }, // младший брат
  {
    title: "Джон Кью",
    original: ["John Q"],
    release: "2002-02-15",
    publish: "2025-07-29T07:27:31",
    directors: ["Ник Кассаветис"],
    format: "фильм",
    liked: "dislike",
    screenshots: 45,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/720/",
  }, // джон кью
  {
    title: "Голубой байу",
    original: ["Blue Bayou", "Синий залив"],
    release: "2021-09-17",
    publish: "2025-07-28T07:05:34",
    directors: ["Джастин Чон"],
    format: "фильм",
    liked: "like",
    screenshots: 75,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1313196/",
  }, // голубой байу
  {
    title: "Слоеный торт",
    original: ["Layer Cake"],
    release: "2004-10-01",
    publish: "2025-07-24T14:58:18",
    directors: ["Мэттью Вон"],
    format: "фильм",
    liked: "like",
    screenshots: 51,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/47250/",
  }, // слоеный торт
  {
    title: "Последний самурай",
    original: ["The Last Samurai"],
    release: "2003-12-05",
    publish: "2025-07-24T11:03:09",
    directors: ["Эдвард Цвик"],
    format: "фильм",
    liked: "like",
    screenshots: 90,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/6764/",
  }, // последний самурай
  {
    title: "Мармелад",
    original: ["Marmalade"],
    release: "2024-02-12",
    publish: "2025-07-24T17:53:33",
    directors: ["Кейр О’Доннелл"],
    format: "фильм",
    liked: "like",
    screenshots: 42,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5071324/",
  }, // мармелад
  {
    title: "Соучастник",
    original: ["Collateral"],
    release: "2004-08-06",
    publish: "2025-07-23T19:11:54",
    directors: ["Майкл Манн"],
    format: "фильм",
    liked: "like",
    screenshots: 18,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/61325/",
  }, // соучастник
  {
    title: "Пиджак",
    original: ["The Jacket", "Пиджмак"],
    release: "2005-03-04",
    publish: "2025-07-23T12:03:25",
    directors: ["Джон Мэйбери"],
    format: "фильм",
    liked: "dislike",
    screenshots: 32,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/47382/",
  }, // пиджак
  {
    title: "Поезд на Дарджилинг. Отчаянные путешественники",
    original: ["The Darjeeling Limited"],
    release: "2007-10-26",
    publish: "2025-07-20T11:42:43",
    directors: ["Уэс Андерсон"],
    format: "фильм",
    liked: "like",
    screenshots: 63,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/278185/",
  }, // поезд на дарджилинг
  {
    title: "Братья Супер Марио в кино",
    original: ["The Super Mario Bros. Movie"],
    release: "2023-04-05",
    publish: "2025-07-20T18:05:35",
    directors: ["Аарон Хорват", "Михаэль Еленик", "Пьер Ледюк"],
    format: "фильм",
    liked: "like",
    screenshots: 33,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1111005/",
  }, // братья супер марио в кино
  {
    title: "Четыре льва",
    original: ["Four Lions", "4 Lions"],
    release: "2010-05-07",
    publish: "2025-07-19T23:45:24",
    directors: ["Кристофер Моррис"],
    format: "фильм",
    liked: "like",
    screenshots: 14,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/448665/",
  }, // четыре льва
  {
    title: "Фантастическая четверка",
    original: ["Fantastic Four"],
    release: "2005-07-08",
    publish: "2025-07-14T23:00:34",
    directors: ["Тим Стори"],
    format: "фильм",
    liked: "like",
    screenshots: 42,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/23263/",
  }, // фантастическая четверка (2005)
  {
    title: "Хищник: Убийца убийц",
    original: ["Predator: Killer of Killers"],
    release: "2025-06-06",
    publish: "2025-07-13T13:51:14",
    directors: ["Дэн Трахтенберг", "Джошуа Вассунг"],
    format: "фильм",
    liked: "like",
    screenshots: 51,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/7596122/",
  }, // хищник: убийца убийц
  {
    title: "Король Ричард",
    original: ["King Richard"],
    release: "2021-11-19",
    publish: "2025-07-12T10:13:10",
    directors: ["Рейнальдо Маркус Грин"],
    operator: "Роберт Элсвит",
    format: "фильм",
    liked: "like",
    screenshots: 26,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1272469/",
  }, // король ричард
  {
    title: "Громовержцы*",
    original: ["Thunderbolts*", "New Avengers", "Новые Мстители"],
    release: "2025-05-02",
    publish: "2025-07-23T16:20:14",
    directors: ["Джейк Шрейер"],
    format: "фильм",
    liked: "like",
    screenshots: 66,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5001443/",
  }, // громовержцы*
  {
    title: "Грешники",
    original: ["Sinners"],
    release: "2025-04-18",
    publish: "2025-07-08T07:17:58",
    directors: ["Райан Куглер"],
    format: "фильм",
    liked: "like",
    screenshots: 51,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5499518/",
  }, // грешники
  {
    title: "Кто угодно, кроме тебя",
    original: ["Anyone But You"],
    release: "2023-12-22",
    publish: "2025-06-29T18:02:03",
    directors: ["Уилл Глак"],
    format: "фильм",
    liked: "like",
    screenshots: 32,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5305423/",
  }, // кто угодно, кроме тебя
  {
    title: "На вершине горы",
    original: ["Mountainhead"],
    release: "2025-05-31",
    publish: "2025-06-21T13:03:14",
    directors: ["Джесси Армстронг"],
    format: "фильм",
    liked: "dislike",
    screenshots: 27,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/7770979/",
  }, // на вершине горы
  {
    title: "Киностудия",
    original: ["The Studio"],
    release: "2025-03-26",
    publish: "2025-06-21T10:18:31",
    directors: ["Эван Голдберг", "Сет Роген"],
    format: "сериал",
    season: "1",
    isMiniSeries: false,
    liked: "like",
    screenshots: 23,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/6579800/",
  }, // киностудия 1
  {
    title: "Уимблдон",
    original: ["Wimbledon"],
    release: "2004-09-17",
    publish: "2025-06-14T15:36:43",
    directors: ["Ричард Лонкрэйн"],
    format: "фильм",
    liked: "dislike",
    screenshots: 17,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/19174/",
  }, // уимблдон
  {
    title: "Лило и Стич",
    original: ["Lilo & Stitch"],
    release: "2002-06-21",
    publish: "2025-06-08T11:08:27",
    directors: ["Дин ДеБлуа", "Крис Сандерс"],
    format: "фильм",
    liked: "like",
    screenshots: 42,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/740/",
  }, // лило и стич (2002)
  {
    title: "Опус",
    original: ["Opus"],
    release: "2025-03-14",
    publish: "2025-06-01T11:34:14",
    directors: ["Марк Энтони Грин"],
    format: "фильм",
    liked: "dislike",
    screenshots: 24,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/6718282/",
  }, // опус
  {
    title: "Любовь. Смерть. Роботы",
    original: ["Love, Death & Robots"],
    release: "2025-05-15",
    publish: "2025-06-01T15:45:35",
    creators: ["Тим Миллер"],
    format: "сериал",
    season: "4",
    isMiniSeries: false,
    liked: "like",
    screenshots: 20,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/1228254/",
  }, // любовь, смерть и роботы 4
  {
    title: "Смерть единорога",
    original: ["Death of a Unicorn"],
    release: "2025-03-14",
    publish: "2025-05-31T11:37:25",
    directors: ["Алекс Шарфман"],
    format: "фильм",
    liked: "dislike",
    screenshots: 24,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5445197/",
  }, // смерть единорога
  {
    title: "Оценка",
    original: ["The Assessment"],
    release: "2024-09-08",
    publish: "2025-05-31T13:57:00",
    directors: ["Флёр Форчун"],
    format: "фильм",
    liked: "dislike",
    screenshots: 63,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/6042919/",
  }, // оценка
  {
    title: "Маленькая барабанщица",
    original: ["The Little Drummer Girl"],
    release: "2018-10-18",
    publish: "2025-05-28T08:07:07",
    directors: ["Пак Чхан-ук"],
    format: "сериал",
    isMiniSeries: true,
    liked: "dislike",
    screenshots: 18,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/1100408/",
  }, // маленькая барабанщица
  {
    title: "Недруги",
    original: ["Hostiles"],
    release: "2017-09-02",
    publish: "2025-05-25T13:52:44",
    directors: ["Скотт Купер"],
    format: "фильм",
    liked: "dislike",
    screenshots: 30,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/963016/",
  }, // недруги
  {
    title: "Как трусливый Роберт Форд убил Джесси Джеймса",
    original: ["The Assassination of Jesse James by the Coward Robert Ford"],
    release: "2007-10-19",
    publish: "2025-05-25T09:20:23",
    directors: ["Эндрю Доминик"],
    operator: "Роджер Дикинс",
    format: "фильм",
    liked: "dislike",
    screenshots: 30,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/102127/",
  }, // как трусливый роберт форд убил джесси джеймса
  {
    title: "Быстрый и мертвый",
    original: ["The Quick and the Dead"],
    release: "1995-02-10",
    publish: "2025-05-23T21:02:13",
    directors: ["Сэм Рэйми"],
    format: "фильм",
    liked: "like",
    screenshots: 24,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/2273/",
  }, // быстрый и мертвый
  {
    title: "Омерзительная восьмерка",
    original: ["The Hateful Eight", "The Hateful 8"],
    release: "2015-12-30",
    publish: "2025-05-17T10:17:07",
    directors: ["Квентин Тарантино"],
    operator: "Роберт Ричардсон",
    format: "фильм",
    liked: "like",
    screenshots: 77,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/819101/",
  }, // омерзительная восьмерка
  {
    title: "Поезд на Юму",
    original: ["3:10 to Yuma"],
    release: "2007-09-07",
    publish: "2025-05-11T12:04:39",
    directors: ["Джеймс Мэнголд"],
    format: "фильм",
    liked: "like",
    screenshots: 27,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/78240/",
  }, // поезд на юму
  {
    title: "Падение империи",
    original: ["Civil War"],
    release: "2024-04-12",
    publish: "2025-05-09T12:30:23",
    directors: ["Алекс Гарленд"],
    format: "фильм",
    liked: "like",
    screenshots: 24,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/4968810/",
  }, // падение империи
  {
    title: "Друзья навсегда",
    original: ["Our Friend"],
    release: "2019-09-06",
    publish: "2025-05-06T17:14:38",
    directors: ["Габриэла Каупертуэйт"],
    format: "фильм",
    liked: "like",
    screenshots: 48,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1231105/",
  }, // друзья навсегда
  {
    title: "Нарковоры",
    original: ["Dope Thief"],
    release: "2025-03-14",
    publish: "2025-05-04T17:02:47",
    format: "сериал",
    season: "1",
    isMiniSeries: false,
    liked: "dislike",
    screenshots: 42,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/5138508/",
  }, // нарковоры 1
  {
    title: "Железная хватка",
    original: ["True Grit"],
    release: "2010-12-22",
    publish: "2025-05-04T21:26:56",
    directors: ["Джоэл Коэн", "Итан Коэн"],
    operator: "Роджер Дикинс",
    format: "фильм",
    liked: "like",
    screenshots: 41,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/462553/",
  }, // железная хватка
  {
    title: "Стальная хватка",
    original: ["The Iron Claw"],
    release: "2023-12-22",
    publish: "2025-05-03T18:53:41",
    directors: ["Шон Дуркин"],
    format: "фильм",
    liked: "like",
    screenshots: 63,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5005446/",
  }, // стальная хватка
  {
    title: "Формула 1. Драйв выживания",
    original: ["Formula 1: Drive to Survive"],
    release: "2025-03-07",
    publish: "2025-05-03T15:36:46",
    format: "сериал",
    season: "7",
    isMiniSeries: false,
    liked: "like",
    screenshots: 47,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/1240162/",
  }, // формула 1. драйв выживания 7
  {
    title: "Тот самый день",
    original: ["One of Them Days", "Один из этих дней"],
    release: "2025-01-17",
    publish: "2025-04-29T09:02:30",
    directors: ["Лоуренс Ламонт"],
    format: "фильм",
    liked: "dislike",
    screenshots: 15,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/7002807/",
  }, // тот самый день
  {
    title: "Жажда славы",
    original: ["Magazine Dreams"],
    release: "2023-01-20",
    publish: "2025-04-28T20:31:55",
    directors: ["Элайджа Байнум"],
    format: "фильм",
    liked: "dislike",
    screenshots: 60,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/4704816/",
  }, // жажда славы
  {
    title: "Чёрный чемодан – двойная игра",
    original: ["Black Bag"],
    release: "2025-03-14",
    publish: "2025-04-18T20:42:38",
    directors: ["Стивен Содерберг"],
    format: "фильм",
    liked: "like",
    screenshots: 48,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5449060/",
  }, // чёрный чемодан – двойная игра
  {
    title: "Фримонт. Американская мечта",
    original: ["Fremont"],
    release: "2023-10-10",
    publish: "2025-04-13T10:55:46",
    directors: ["Бабак Джалали"],
    format: "фильм",
    liked: "like",
    screenshots: 60,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5108082/",
  }, // фримонт
  {
    title: "Подземелья и драконы: Честь среди воров",
    original: ["Dungeons & Dragons: Honor Among Thieves"],
    release: "2023-03-31",
    publish: "2025-04-06T10:30:32",
    directors: ["Джон Фрэнсис Дейли", "Джонатан М. Голдштейн"],
    format: "фильм",
    liked: "like",
    screenshots: 18,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/762646/",
  }, // подземелья и драконы: честь среди воров
  {
    title: "Микки 17",
    original: ["Mickey 17"],
    release: "2025-03-07",
    publish: "2025-04-06T23:17:48",
    directors: ["Пон Джун-хо"],
    operator: "Дариус Хонджи",
    format: "фильм",
    liked: "dislike",
    screenshots: 66,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1320476/",
  }, // микки 17
  {
    title: "Любой ценой",
    original: ["Hell or High Water"],
    release: "2016-08-26",
    publish: "2025-04-06T19:22:27",
    directors: ["Дэвид Маккензи"],
    format: "фильм",
    liked: "like",
    screenshots: 33,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/726794/",
  }, // любой ценой
  {
    title: "Варвар",
    original: ["Barbarian"],
    release: "2022-09-09",
    publish: "2025-04-06T11:47:45",
    directors: ["Зак Креггер"],
    format: "фильм",
    liked: "like",
    screenshots: 50,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/4749790/",
  }, // варвар
  {
    title: "Частые побочные явления",
    original: ["Common Side Effects", "Обычные побочки"],
    release: "2025-02-02",
    publish: "2025-04-05T16:52:19",
    format: "сериал",
    season: "1",
    isMiniSeries: false,
    liked: "like",
    screenshots: 36,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/6990425/",
  }, // частые побочные явления 1
  {
    title: "Голый пистолет",
    original: ["The Naked Gun: From the Files of Police Squad!"],
    release: "1988-12-02",
    publish: "2025-04-05T09:24:15",
    directors: ["Дэвид Цукер"],
    format: "фильм",
    liked: "like",
    screenshots: 23,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/4067/",
  }, // голый пистолет (1988)
  {
    title: "Разделение",
    original: ["Severance"],
    release: "2025-01-17",
    publish: "2025-04-04T23:10:03",
    creators: ["Бен Стиллер", "Дэн Эриксон"],
    format: "сериал",
    season: "2",
    isMiniSeries: false,
    liked: "like",
    screenshots: 237,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/1343318/",
  }, // разделение 2
  {
    title: "Суперсемейка 2",
    original: ["Incredibles 2"],
    release: "2018-06-15",
    publish: "2025-03-30T20:46:55",
    directors: ["Брэд Бёрд"],
    format: "фильм",
    liked: "like",
    screenshots: 87,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/839650/",
  }, // суперсемейка 2
  {
    title: "Суперсемейка",
    original: ["The Incredibles"],
    release: "2004-11-05",
    publish: "2025-03-30T17:28:07",
    directors: ["Брэд Бёрд"],
    format: "фильм",
    liked: "like",
    screenshots: 27,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/38903/",
  }, // суперсемейка
  {
    title: "Мегамозг",
    original: ["Megamind"],
    release: "2010-11-05",
    publish: "2025-03-29T18:21:19",
    directors: ["Том МакГрат"],
    format: "фильм",
    liked: "like",
    screenshots: 30,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/405608/",
  }, // мегамозг
  {
    title: "Кровью и потом: Анаболики",
    original: ["Pain & Gain", "Анатолики"],
    release: "2013-04-26",
    publish: "2025-03-29T16:06:51",
    directors: ["Майкл Бэй"],
    format: "фильм",
    liked: "like",
    screenshots: 69,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/596227/",
  }, // кровью и потом: анаболики
  {
    title: "Жаркие летние ночи",
    original: ["Hot Summer Nights"],
    release: "2018-07-27",
    publish: "2025-03-29T22:05:00",
    directors: ["Элайджа Байнум"],
    format: "фильм",
    liked: "like",
    screenshots: 42,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/928993/",
  }, // жаркие летние ночи
  {
    title: "Проект Флорида",
    original: ["The Florida Project"],
    release: "2017-11-10",
    publish: "2025-03-28T15:50:29",
    directors: ["Шон Бэйкер"],
    format: "фильм",
    liked: "like",
    screenshots: 48,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/998317/",
  }, // проект флорида
  {
    title: "Маяк",
    original: ["The Lighthouse"],
    release: "2019-11-01",
    publish: "2025-03-26T17:22:10",
    directors: ["Роберт Эггерс"],
    format: "фильм",
    liked: "like",
    screenshots: 81,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1114927/",
  }, // маяк
  {
    title: "Лига справедливости Зака Снайдера: Черно-белая версия",
    original: ["Zack Snyder's Justice League: Justice Is Gray"],
    release: "2021-03-18",
    publish: "2025-03-26T11:03:58",
    directors: ["Зак Снайдер"],
    format: "фильм",
    liked: "dislike",
    screenshots: 126,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/4404112/",
  }, // лига справедливости зака снайдера
  {
    title: "Безумный Макс: Дорога ярости. Чёрно-белое издание",
    original: ["Mad Max: Fury Road Black And Chrome Edition"],
    release: "2016-12-01",
    publish: "2025-03-25T11:43:01",
    directors: ["Джордж Миллер"],
    format: "фильм",
    liked: "like",
    screenshots: 54,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/453406/",
  }, // безумный макс. чёрно-белое издание
  {
    title: "Синг-Синг",
    original: ["Sing Sing"],
    release: "2024-08-02",
    publish: "2025-03-21T20:44:06",
    directors: ["Грег Куидар"],
    format: "фильм",
    liked: "like",
    screenshots: 54,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5378058/",
  }, // синг-синг
  {
    title: "Отряд самоубийц: Миссия навылет",
    original: ["The Suicide Squad"],
    release: "2021-08-05",
    publish: "2025-03-21T18:13:46",
    directors: ["Джеймс Ганн"],
    format: "фильм",
    liked: "like",
    screenshots: 57,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1008477/",
  }, // отряд самоубийц: миссия навылет
  {
    title: "Книга джунглей",
    original: ["The Jungle Book"],
    release: "2016-04-15",
    publish: "2025-03-21T12:53:18",
    directors: ["Джон Фавро"],
    format: "фильм",
    liked: "like",
    screenshots: 36,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/779024/",
  }, // книга джунглей
  {
    title: "Присутствие",
    original: ["Presence"],
    release: "2024-01-19",
    publish: "2025-03-20T21:35:43",
    directors: ["Стивен Содерберг"],
    format: "фильм",
    liked: "like",
    screenshots: 21,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5445463/",
  }, // присутствие
  {
    title: "Логан: Нуар",
    original: ["Logan: Noir"],
    release: "2017-05-16",
    publish: "2025-03-20T15:44:28",
    directors: ["Джеймс Мэнголд"],
    format: "фильм",
    liked: "like",
    screenshots: 90,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/807682/",
  }, // логан: нуар
  {
    title: "Город воров",
    original: ["The Town"],
    release: "2010-09-17",
    publish: "2025-03-20T10:08:57",
    directors: ["Бен Аффлек"],
    operator: "Роберт Элсвит",
    format: "фильм",
    liked: "like",
    screenshots: 47,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/462732/",
  }, // город воров
  {
    title: "Непобедимый",
    original: ["Invincible"],
    release: "2025-02-06",
    publish: "2025-03-18T14:56:33",
    creators: ["Роберт Киркман"],
    format: "сериал",
    season: "3",
    isMiniSeries: false,
    liked: "like",
    screenshots: 57,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/1171895/",
  }, // непобедимый 3
  {
    title: "Бегущий по лезвию 2049",
    original: ["Blade Runner 2049"],
    release: "2017-10-06",
    publish: "2025-03-17T13:03:52",
    directors: ["Дени Вильнёв"],
    operator: "Роджер Дикинс",
    format: "фильм",
    liked: "like",
    screenshots: 81,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/589290/",
  }, // бегущий по лезвию 2049
  {
    title: "Враг",
    original: ["Enemy"],
    release: "2013-09-08",
    publish: "2025-03-13T19:01:45",
    directors: ["Дени Вильнёв"],
    format: "фильм",
    liked: "like",
    screenshots: 48,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/673910/",
  }, // враг
  {
    title: "Мстители: Эра Альтрона",
    original: ["Avengers: Age of Ultron"],
    release: "2015-05-01",
    publish: "2025-03-08T00:37:12",
    directors: ["Джосс Уидон"],
    format: "фильм",
    liked: "like",
    screenshots: 48,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/679830/",
  }, // мстители: эра альтрона
  {
    title: "Топ Ган: Мэверик",
    original: ["Top Gun: Maverick"],
    release: "2022-05-27",
    publish: "2025-03-02T17:10:20",
    directors: ["Джозеф Косински"],
    format: "фильм",
    liked: "like",
    screenshots: 96,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/572032/",
  }, // топ ган: мэверик
  {
    title: "Вавилон",
    original: ["Babel"],
    release: "2006-11-10",
    publish: "2025-03-02T11:52:15",
    directors: ["Алехандро Гонсалес Иньярриту"],
    format: "фильм",
    liked: "dislike",
    screenshots: 27,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/102125/",
  }, // вавилон (2006)
  {
    title: "Белфаст",
    original: ["Belfast"],
    release: "2021-11-12",
    publish: "2025-03-01T19:08:31",
    directors: ["Кеннет Брана"],
    format: "фильм",
    liked: "like",
    screenshots: 69,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1397888/",
  }, // белфаст
  {
    title: "Пожары",
    original: ["Incendies"],
    release: "2010-09-03",
    publish: "2025-03-01T23:24:09",
    directors: ["Дени Вильнёв"],
    format: "фильм",
    liked: "like",
    screenshots: 53,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/425400/",
  }, // пожары
  {
    title: "Мстители: Финал",
    original: ["Avengers: Endgame"],
    release: "2019-04-26",
    publish: "2025-03-01T02:36:12",
    directors: ["Джо Руссо", "Энтони Руссо"],
    format: "фильм",
    liked: "like",
    screenshots: 69,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/843650/",
  }, // мстители: финал
  {
    title: "Мстители: Война бесконечности",
    original: ["Avengers: Infinity War"],
    release: "2018-04-27",
    publish: "2025-02-28T22:25:17",
    directors: ["Джо Руссо", "Энтони Руссо"],
    format: "фильм",
    liked: "like",
    screenshots: 89,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/843649/",
  }, // мстители: война бесконечности
  {
    title: "Вершина богов",
    original: ["The Summit of the Gods", "Le sommet des dieux"],
    release: "2021-11-30",
    publish: "2025-02-28T18:40:01",
    directors: ["Патрик Имбер"],
    format: "фильм",
    liked: "like",
    screenshots: 57,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1090932/",
  }, // вершина богов
  {
    title: "Ущелье",
    original: ["The Gorge"],
    release: "2025-02-14",
    publish: "2025-02-22T17:06:54",
    directors: ["Скотт Дерриксон"],
    format: "фильм",
    liked: "dislike",
    screenshots: 48,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5098653/",
  }, // ущелье
  {
    title: "Трансформеры: Начало",
    original: ["Transformers One"],
    release: "2024-09-20",
    publish: "2025-02-22T13:07:42",
    directors: ["Джош Кули"],
    format: "фильм",
    liked: "like",
    screenshots: 24,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1229682/",
  }, // трансформеры: начало
  {
    title: "Бруталист",
    original: ["The Brutalist"],
    release: "2024-09-01",
    publish: "2025-02-21T21:52:44",
    directors: ["Брэйди Корбе"],
    format: "фильм",
    liked: "dislike",
    screenshots: 72,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1405331/",
  }, // бруталист
  {
    title: "Рома",
    original: ["Roma"],
    release: "2018-12-14",
    publish: "2025-02-17T07:35:43",
    directors: ["Альфонсо Куарон"],
    format: "фильм",
    liked: "like",
    screenshots: 39,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1008486/",
  }, // рома
  {
    title: "Неудержимый",
    original: ["Unstoppable", "Неукротимый"],
    release: "2024-09-06",
    publish: "2025-02-13T19:55:01",
    directors: ["Уильям Голденберг"],
    format: "фильм",
    liked: "like",
    screenshots: 42,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5455286/",
  }, // неудержимый
  {
    title: "Сорвиголова",
    original: ["Daredevil"],
    release: "2016-03-18",
    publish: "2025-02-02T20:47:46",
    creators: ["Дрю Годдард"],
    format: "сериал",
    season: "2",
    isMiniSeries: false,
    liked: "like",
    screenshots: 46,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/817509/",
  }, // сорвиголова 2
  {
    title: "Тренировочный день",
    original: ["Training Day"],
    release: "2001-10-05",
    publish: "2025-01-25T17:51:45",
    directors: ["Антуан Фукуа"],
    format: "фильм",
    liked: "like",
    screenshots: 44,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/863/",
  }, // тренировочный день
  {
    title: "Сокровище нации: Книга Тайн",
    original: ["National Treasure: Book of Secrets"],
    release: "2007-12-21",
    publish: "2025-01-26T11:21:58",
    directors: ["Джон Тёртлтауб"],
    format: "фильм",
    liked: "like",
    screenshots: 17,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/195408/",
  }, // сокровище нации: книга тайн
  {
    title: "Сокровище нации",
    original: ["National Treasure"],
    release: "2004-11-19",
    publish: "2025-01-25T14:11:06",
    directors: ["Джон Тёртлтауб"],
    format: "фильм",
    liked: "like",
    screenshots: 14,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/61333/",
  }, // сокровище нации
  {
    title: "Идеальный шторм",
    original: ["The Perfect Storm"],
    release: "2000-06-30",
    publish: "2025-01-24T19:42:57",
    directors: ["Вольфганг Петерсен"],
    format: "фильм",
    liked: "dislike",
    screenshots: 12,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/783/",
  }, // идеальный шторм
  {
    title: "Не пойман – не вор",
    original: ["Inside Man"],
    release: "2006-03-24",
    publish: "2025-01-19T13:04:41",
    directors: ["Спайк Ли"],
    format: "фильм",
    liked: "like",
    screenshots: 16,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/103785/",
  }, // не пойман не вор
  {
    title: "Лэндмен",
    original: ["Landman", "Землевладелец"],
    release: "2024-11-17",
    publish: "2025-01-19T18:02:12",
    creators: ["Тейлор Шеридан"],
    format: "сериал",
    season: "1",
    isMiniSeries: false,
    liked: "like",
    screenshots: 36,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/4909559/",
  }, // лэндмен 1
  {
    title: "Монстры-коммандос",
    original: ["Creature Commandos"],
    release: "2024-12-05",
    publish: "2025-01-12T10:10:47",
    creators: ["Джеймс Ганн"],
    format: "сериал",
    season: "1",
    isMiniSeries: false,
    liked: "like",
    screenshots: 33,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/5253831/",
  }, // монстры-коммандос 1
  {
    title: "Настоящая боль",
    original: ["A Real Pain"],
    release: "2024-11-15",
    publish: "2025-01-04T16:07:41",
    directors: ["Джесси Айзенберг"],
    format: "фильм",
    liked: "dislike",
    screenshots: 21,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5105866/",
  }, // настоящая боль
  {
    title: "Хоббит: Битва пяти воинств",
    original: ["The Hobbit: The Battle of the Five Armies"],
    release: "2014-12-17",
    publish: "2024-12-27T21:15:55",
    directors: ["Питер Джексон"],
    format: "фильм",
    liked: "like",
    screenshots: 15,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/694633/",
  }, // хоббит: битва пяти воинств (3)
  {
    title: "Хоббит: Пустошь Смауга",
    original: ["The Hobbit: The Desolation of Smaug"],
    release: "2013-12-13",
    publish: "2024-12-26T20:14:49",
    directors: ["Питер Джексон"],
    format: "фильм",
    liked: "like",
    screenshots: 22,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/408876/",
  }, // хоббит: пустошь смауга (2)
  {
    title: "Хоббит: Нежданное путешествие",
    original: ["The Hobbit: An Unexpected Journey"],
    release: "2012-12-14",
    publish: "2024-12-23T23:53:54",
    directors: ["Питер Джексон"],
    format: "фильм",
    liked: "like",
    screenshots: 40,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/278522/",
  }, // хоббит: нежданное путешествие (1)
  {
    title: "Идеальные дни",
    original: ["Perfect Days"],
    release: "2023-05-25",
    publish: "2024-12-15T12:37:54",
    directors: ["Вим Вендерс"],
    format: "фильм",
    liked: "like",
    screenshots: 59,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5283168/",
  }, // идеальные дни
  {
    title: "Его три дочери",
    original: ["His Three Daughters"],
    release: "2024-09-20",
    publish: "2024-12-15T19:10:39",
    directors: ["Азазель Джейкобс"],
    format: "фильм",
    liked: "like",
    screenshots: 39,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5368757/",
  }, // его три дочери
  {
    title: "Сёгун",
    original: ["Shogun", "Shôgun"],
    release: "2024-02-27",
    publish: "2024-12-14T18:27:57",
    format: "сериал",
    season: "1",
    isMiniSeries: false,
    liked: "dislike",
    screenshots: 45,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/749562/",
  }, // сёгун 1
  {
    title: "Аркейн",
    original: ["Arcane: League of Legends"],
    release: "2024-11-09",
    publish: "2024-11-23T20:20:28",
    format: "сериал",
    season: "2",
    isMiniSeries: false,
    liked: "like",
    screenshots: 59,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/4445150/",
  }, // aркейн 2
  {
    title: "Аркейн",
    original: ["Arcane: League of Legends"],
    release: "2021-11-06",
    publish: "2024-11-21T19:25:41",
    format: "сериал",
    season: "1",
    isMiniSeries: false,
    liked: "like",
    screenshots: 54,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/4445150/",
  }, // aркейн 1
  {
    title: "Пингвин",
    original: ["The Penguin"],
    release: "2024-09-19",
    publish: "2024-11-15T07:36:10",
    format: "сериал",
    isMiniSeries: true,
    liked: "like",
    screenshots: 33,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/4635062/",
  }, // пингвин
  {
    title: "Это всё Агата",
    original: ["Agatha All Along"],
    release: "2024-09-18",
    publish: "2024-11-03T12:12:58",
    format: "сериал",
    isMiniSeries: true,
    liked: "like",
    screenshots: 21,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/402955/",
  }, // это всё агата
  {
    title: "Дикий робот",
    original: ["The Wild Robot"],
    release: "2024-09-27",
    publish: "2024-10-27T13:57:31",
    directors: ["Крис Сандерс"],
    format: "фильм",
    liked: "like",
    screenshots: 25,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5457899/",
  }, // дикий робот
  {
    title: "Прослушка",
    original: ["The Wire"],
    release: "2008-01-06",
    publish: "2024-10-26T14:02:47",
    creators: ["Дэвид Саймон"],
    format: "сериал",
    season: "5",
    isMiniSeries: false,
    liked: "like",
    screenshots: 47,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/402955/",
  }, // прослушка 5
  {
    title: "Прослушка",
    original: ["The Wire"],
    release: "2006-09-10",
    publish: "2024-10-14T07:40:33",
    creators: ["Дэвид Саймон"],
    format: "сериал",
    season: "4",
    isMiniSeries: false,
    liked: "like",
    screenshots: 65,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/402955/",
  }, // прослушка 4
  {
    title: "The Vince Staples Show",
    original: ["The Vince Staples Show"],
    release: "2024-02-15",
    publish: "2024-09-10T20:49:32",
    creators: ["Йен Эдельман", "Винс Стэйплс", "Морис Уильямс"],
    format: "сериал",
    season: "1",
    isMiniSeries: false,
    liked: "like",
    screenshots: 19,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/5450042/",
  }, // vince staples show
  {
    title: "Район №9",
    original: ["District 9"],
    release: "2009-08-14",
    publish: "2024-10-02T14:43:16",
    directors: ["Нил Бломкамп"],
    format: "фильм",
    liked: "like",
    screenshots: 11,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/397494/",
  }, // район № 9
  {
    title: "Подай знак",
    original: ["Blink Twice"],
    release: "2024-08-23",
    publish: "2024-10-01T12:33:13",
    directors: ["Зои Кравиц"],
    format: "фильм",
    liked: "like",
    screenshots: 33,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/4630624/",
  }, // подай знак
  {
    title: "Одинокие волки",
    original: ["Wolfs"],
    release: "2024-09-27",
    publish: "2024-10-01T19:40:30",
    directors: ["Джон Уоттс"],
    format: "фильм",
    liked: "dislike",
    screenshots: 30,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/4825582/",
  }, // одинокие волки
  {
    title: "Гранд тур",
    original: ["The Grand Tour"],
    release: "2024-09-13",
    publish: "2024-09-30T15:32:27",
    format: "сериал",
    season: "6",
    isMiniSeries: false,
    liked: "like",
    screenshots: 20,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/982730/",
  }, // гранд тур 6
  {
    title: "Барри",
    original: ["Barry"],
    release: "2023-04-16",
    publish: "2024-09-08T21:07:28",
    creators: ["Алек Берг", "Билл Хейдер"],
    format: "сериал",
    season: "4",
    isMiniSeries: false,
    liked: "like",
    screenshots: 28,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/972587/",
  }, // барри 4
  {
    title: "Барри",
    original: ["Barry"],
    release: "2022-04-24",
    publish: "2024-09-08T14:14:03",
    creators: ["Алек Берг", "Билл Хейдер"],
    format: "сериал",
    season: "3",
    isMiniSeries: false,
    liked: "like",
    screenshots: 27,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/972587/",
  }, // барри 3
  {
    title: "Барри",
    original: ["Barry"],
    release: "2019-03-31",
    publish: "2024-09-08T09:04:35",
    creators: ["Алек Берг", "Билл Хейдер"],
    format: "сериал",
    season: "2",
    isMiniSeries: false,
    liked: "like",
    screenshots: 25,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/972587/",
  }, // барри 2
  {
    title: "Барри",
    original: ["Barry"],
    release: "2018-03-25",
    publish: "2024-09-07T12:44:42",
    creators: ["Алек Берг", "Билл Хейдер"],
    format: "сериал",
    season: "1",
    isMiniSeries: false,
    liked: "like",
    screenshots: 21,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/972587/",
  }, // барри 1

  {
    title: "Формула 1. Драйв выживания",
    original: ["Formula 1: Drive to Survive"],
    release: "2024-02-23",
    publish: "2024-07-21T23:42:09",
    format: "сериал",
    season: "6",
    isMiniSeries: false,
    liked: "like",
    screenshots: 24,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/1240162/",
  }, // формула 1. драйв выживания 6
  {
    title: "Формула 1. Драйв выживания",
    original: ["Formula 1: Drive to Survive"],
    release: "2023-02-24",
    publish: "2024-07-14T11:36:49",
    format: "сериал",
    season: "5",
    isMiniSeries: false,
    liked: "like",
    screenshots: 23,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/1240162/",
  }, // формула 1. драйв выживания 5
  {
    title: "Непобедимый",
    original: ["Invincible"],
    release: "2023-11-03",
    publish: "2024-04-16T20:44:08",
    creators: ["Роберт Киркман"],
    format: "сериал",
    season: "2",
    isMiniSeries: false,
    liked: "like",
    screenshots: 29,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/1171895/",
  }, // непобедимый 2
  {
    title: "Сорвиголова",
    original: ["Daredevil"],
    release: "2015-04-10",
    publish: "2024-03-02T09:55:37",
    creators: ["Дрю Годдард"],
    format: "сериал",
    season: "1",
    isMiniSeries: false,
    liked: "like",
    screenshots: 29,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/817509/",
  }, // сорвиголова 1
  {
    title: "Харли Квинн",
    original: ["Harley Quinn"],
    release: "2023-07-27",
    publish: "2023-10-07T22:51:54",
    format: "сериал",
    season: "1-4",
    releaseDates: ["2019-11-29", "2020-04-03", "2022-07-28", "2023-07-27"],
    isMiniSeries: false,
    liked: "like",
    screenshots: 22,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/1112514/",
  }, // харли квинн 1-4
  {
    title: "Разделение",
    original: ["Severance"],
    release: "2022-02-18",
    publish: "2022-04-27T21:06:25",
    creators: ["Бен Стиллер", "Дэн Эриксон"],
    format: "сериал",
    season: "1",
    isMiniSeries: false,
    liked: "like",
    screenshots: 74,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/1343318/",
  }, // разделение 1
  {
    title: "Непобедимый",
    original: ["Invincible"],
    release: "2021-03-26",
    publish: "2021-05-09T22:03:03",
    creators: ["Роберт Киркман"],
    format: "сериал",
    season: "1",
    isMiniSeries: false,
    liked: "like",
    screenshots: 21,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/1171895/",
  }, // непобедимый 1
]; // ГЛАВНЫЙ МАССИВ
