export const movies = [
  {
    title: "Медведь",
    original: ["The Bear"],
    release: "2025-06-25",
    publish: "2025-09-06T19:31:46",
    format: "сериал",
    season: "4",
    isMiniSeries: false,
    liked: "like",
    screenshots: 60,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/4481731/",
  }, // медведь 4
  {
    title: "Голый пистолет",
    original: ["The Naked Gun"],
    release: "2025-08-01",
    publish: "2025-09-06T16:11:52",
    directors: ["Акива Шаффер"],
    format: "фильм",
    liked: "like",
    screenshots: 21,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/817971/",
  }, // голый пистолет (2025)
  {
    title: "Элио",
    original: ["Elio"],
    release: "2025-06-20",
    publish: "2025-08-30T14:54:55",
    directors: ["Эдриан Молина", "Мадлен Шарафьян", "Доми Ши"],
    format: "фильм",
    liked: "dislike",
    screenshots: 54,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/4893253/",
  }, // элио
  {
    title: "Рик и Морти",
    original: ["Rick and Morty"],
    release: "2025-05-25",
    publish: "2025-08-30T11:38:41",
    creators: ["Дэн Хармон", "Джастин Ройланд"],
    format: "сериал",
    season: "8",
    isMiniSeries: false,
    liked: "like",
    screenshots: 26,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/685246/",
  }, // рик и морти 8
  {
    title: "Супермен",
    original: ["Superman"],
    release: "2025-07-11",
    publish: "2025-08-26T07:46:23",
    directors: ["Джеймс Ганн"],
    format: "фильм",
    liked: "like",
    screenshots: 30,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/997647/",
  }, // супермен
  {
    title: "Стерилизован",
    original: ["Fixed"],
    release: "2025-08-13",
    publish: "2025-08-24T07:35:20",
    directors: ["Генндий Тартаковский"],
    format: "фильм",
    liked: "dislike",
    screenshots: 24,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/4695962/",
  }, // стерилизован
  {
    title: "Миссия невыполнима: Финальная расплата",
    original: ["Mission: Impossible - The Final Reckoning"],
    release: "2025-05-23",
    publish: "2025-08-21T20:42:26",
    directors: ["Кристофер Маккуорри"],
    format: "фильм",
    liked: "like",
    screenshots: 35,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1229683/",
  }, // миссия невыполнима: финальная расплата
  {
    title: "Шалом, папик!",
    original: ["Shiva Baby"],
    release: "2020-03-15",
    publish: "2025-08-19T07:11:31",
    directors: ["Эмма Селигман"],
    format: "фильм",
    liked: "like",
    screenshots: 21,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1324912/",
  }, // шалом, папик!
  {
    title: "Прости, детка",
    original: ["Sorry, Baby"],
    release: "2025-07-25",
    publish: "2025-08-17T13:43:40",
    directors: ["Ева Виктор"],
    format: "фильм",
    liked: "like",
    screenshots: 62,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/7092649/",
  }, // прости, детка
  {
    title: "Жизнь Чака",
    original: ["The Life of Chuck"],
    release: "2024-09-06",
    publish: "2025-08-16T16:28:55",
    directors: ["Майк Флэнаган"],
    format: "фильм",
    liked: "dislike",
    screenshots: 45,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5406956/",
  }, // жизнь чака
  {
    title: "Главы государств",
    original: ["Heads of State"],
    release: "2025-07-02",
    publish: "2025-08-16T13:07:36",
    directors: ["Илья Найшуллер"],
    format: "фильм",
    liked: "dislike",
    screenshots: 18,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5278126/",
  }, // главы государств
  {
    title: "Приключения Тинтина: Тайна единорога",
    original: ["The Adventures of Tintin"],
    release: "2011-12-21",
    publish: "2025-08-06T07:41:41",
    directors: ["Стивен Спилберг"],
    format: "фильм",
    liked: "like",
    screenshots: 27,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/406186/",
  }, // приключения тинтина
  {
    title: "Младший брат",
    original: ["Didi", "Dìdi", "弟弟"],
    release: "2024-08-16",
    publish: "2025-08-03T09:52:57",
    directors: ["Шон Ван"],
    format: "фильм",
    liked: "like",
    screenshots: 51,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5448457/",
  }, // младший брат
  {
    title: "Джон Кью",
    original: ["John Q"],
    release: "2002-02-15",
    publish: "2025-07-29T07:27:31",
    directors: ["Ник Кассаветис"],
    format: "фильм",
    liked: "dislike",
    screenshots: 39,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/720/",
  }, // джон кью
  {
    title: "Голубой байу",
    original: ["Blue Bayou", "Синий залив"],
    release: "2021-09-17",
    publish: "2025-07-28T07:05:34",
    directors: ["Джастин Чон"],
    format: "фильм",
    liked: "like",
    screenshots: 54,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1313196/",
  }, // голубой байу
  {
    title: "Слоеный торт",
    original: ["Layer Cake"],
    release: "2004-10-01",
    publish: "2025-07-24T14:58:18",
    directors: ["Мэттью Вон"],
    format: "фильм",
    liked: "like",
    screenshots: 54,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/47250/",
  }, // слоеный торт
  {
    title: "Последний самурай",
    original: ["The Last Samurai"],
    release: "2003-12-05",
    publish: "2025-07-24T11:03:09",
    directors: ["Эдвард Цвик"],
    format: "фильм",
    liked: "like",
    screenshots: 51,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/6764/",
  }, // последний самурай
  {
    title: "Мармелад",
    original: ["Marmalade"],
    release: "2024-02-12",
    publish: "2025-07-24T17:53:33",
    directors: ["Кейр О’Доннелл"],
    format: "фильм",
    liked: "like",
    screenshots: 35,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5071324/",
  }, // мармелад
  {
    title: "Соучастник",
    original: ["Collateral"],
    release: "2004-08-06",
    publish: "2025-07-23T19:11:54",
    directors: ["Майкл Манн"],
    format: "фильм",
    liked: "like",
    screenshots: 30,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/61325/",
  }, // соучастник
  {
    title: "Пиджак",
    original: ["The Jacket", "Пиджмак"],
    release: "2005-03-04",
    publish: "2025-07-23T12:03:25",
    directors: ["Джон Мэйбери"],
    format: "фильм",
    liked: "dislike",
    screenshots: 42,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/47382/",
  }, // пиджак
  {
    title: "Поезд на Дарджилинг. Отчаянные путешественники",
    original: ["The Darjeeling Limited"],
    release: "2007-10-26",
    publish: "2025-07-20T11:42:43",
    directors: ["Уэс Андерсон"],
    format: "фильм",
    liked: "like",
    screenshots: 69,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/278185/",
  }, // поезд на дарджилинг
  {
    title: "Братья Супер Марио в кино",
    original: ["The Super Mario Bros. Movie"],
    release: "2023-04-05",
    publish: "2025-07-20T18:05:35",
    directors: ["Аарон Хорват", "Михаэль Еленик", "Пьер Ледюк"],
    format: "фильм",
    liked: "like",
    screenshots: 38,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1111005/",
  }, // братья супер марио в кино
  {
    title: "Четыре льва",
    original: ["Four Lions", "4 Lions"],
    release: "2010-05-07",
    publish: "2025-07-19T23:45:24",
    directors: ["Кристофер Моррис"],
    format: "фильм",
    liked: "like",
    screenshots: 18,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/448665/",
  }, // четыре льва
  {
    title: "Фантастическая четверка",
    original: ["Fantastic Four"],
    release: "2005-07-08",
    publish: "2025-07-14T23:00:34",
    directors: ["Тим Стори"],
    format: "фильм",
    liked: "like",
    screenshots: 41,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/23263/",
  }, // фантастическая четверка (2005)
  {
    title: "Хищник: Убийца убийц",
    original: ["Predator: Killer of Killers"],
    release: "2025-06-06",
    publish: "2025-07-13T13:51:14",
    directors: ["Дэн Трахтенберг", "Джошуа Вассунг"],
    format: "фильм",
    liked: "like",
    screenshots: 42,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/7596122/",
  }, // хищник: убийца убийц
  {
    title: "Король Ричард",
    original: ["King Richard"],
    release: "2021-11-19",
    publish: "2025-07-12T10:13:10",
    directors: ["Рейнальдо Маркус Грин"],
    operator: "Роберт Элсвит",
    format: "фильм",
    liked: "like",
    screenshots: 18,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1272469/",
  }, // король ричард
  {
    title: "Громовержцы*",
    original: ["Thunderbolts*", "New Avengers", "Новые Мстители"],
    release: "2025-05-02",
    publish: "2025-07-23T16:20:14",
    directors: ["Джейк Шрейер"],
    format: "фильм",
    liked: "like",
    screenshots: 60,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5001443/",
  }, // громовержцы*
  {
    title: "Грешники",
    original: ["Sinners"],
    release: "2025-04-18",
    publish: "2025-07-08T07:17:58",
    directors: ["Райан Куглер"],
    format: "фильм",
    liked: "like",
    screenshots: 36,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5499518/",
  }, // грешники
  {
    title: "Кто угодно, кроме тебя",
    original: ["Anyone But You"],
    release: "2023-12-22",
    publish: "2025-06-29T18:02:03",
    directors: ["Уилл Глак"],
    format: "фильм",
    liked: "like",
    screenshots: 36,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5305423/",
  }, // кто угодно, кроме тебя
  {
    title: "На вершине горы",
    original: ["Mountainhead"],
    release: "2025-05-31",
    publish: "2025-06-21T13:03:14",
    directors: ["Джесси Армстронг"],
    format: "фильм",
    liked: "dislike",
    screenshots: 24,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/7770979/",
  }, // на вершине горы
  {
    title: "Киностудия",
    original: ["The Studio"],
    release: "2025-03-26",
    publish: "2025-06-21T10:18:31",
    directors: ["Эван Голдберг", "Сет Роген"],
    format: "сериал",
    season: "1",
    isMiniSeries: false,
    liked: "like",
    screenshots: 23,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/6579800/",
  }, // киностудия 1
  {
    title: "Уимблдон",
    original: ["Wimbledon"],
    release: "2004-09-17",
    publish: "2025-06-14T15:36:43",
    directors: ["Ричард Лонкрэйн"],
    format: "фильм",
    liked: "dislike",
    screenshots: 17,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/19174/",
  }, // уимблдон
  {
    title: "Лило и Стич",
    original: ["Lilo & Stitch"],
    release: "2002-06-21",
    publish: "2025-06-08T11:08:27",
    directors: ["Дин ДеБлуа", "Крис Сандерс"],
    format: "фильм",
    liked: "like",
    screenshots: 42,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/740/",
  }, // лило и стич (2002)
  {
    title: "Опус",
    original: ["Opus"],
    release: "2025-03-14",
    publish: "2025-06-01T11:34:14",
    directors: ["Марк Энтони Грин"],
    format: "фильм",
    liked: "dislike",
    screenshots: 24,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/6718282/",
  }, // опус
  {
    title: "Любовь. Смерть. Роботы",
    original: ["Love, Death & Robots"],
    release: "2025-05-15",
    publish: "2025-06-01T15:45:35",
    creators: ["Тим Миллер"],
    format: "сериал",
    season: "4",
    isMiniSeries: false,
    liked: "like",
    screenshots: 20,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/1228254/",
  }, // любовь, смерть и роботы 4
  {
    title: "Смерть единорога",
    original: ["Death of a Unicorn"],
    release: "2025-03-14",
    publish: "2025-05-31T11:37:25",
    directors: ["Алекс Шарфман"],
    format: "фильм",
    liked: "dislike",
    screenshots: 20,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5445197/",
  }, // смерть единорога
  {
    title: "Оценка",
    original: ["The Assessment"],
    release: "2024-09-08",
    publish: "2025-05-31T13:57:00",
    directors: ["Флёр Форчун"],
    format: "фильм",
    liked: "dislike",
    screenshots: 63,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/6042919/",
  }, // оценка
  {
    title: "Маленькая барабанщица",
    original: ["The Little Drummer Girl"],
    release: "2018-10-18",
    publish: "2025-05-28T08:07:07",
    directors: ["Пак Чхан-ук"],
    format: "сериал",
    isMiniSeries: true,
    liked: "dislike",
    screenshots: 18,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/1100408/",
  }, // маленькая барабанщица
  {
    title: "Недруги",
    original: ["Hostiles"],
    release: "2017-09-02",
    publish: "2025-05-25T13:52:44",
    directors: ["Скотт Купер"],
    format: "фильм",
    liked: "dislike",
    screenshots: 30,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/963016/",
  }, // недруги
  {
    title: "Как трусливый Роберт Форд убил Джесси Джеймса",
    original: ["The Assassination of Jesse James by the Coward Robert Ford"],
    release: "2007-10-19",
    publish: "2025-05-25T09:20:23",
    directors: ["Эндрю Доминик"],
    operator: "Роджер Дикинс",
    format: "фильм",
    liked: "dislike",
    screenshots: 36,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/102127/",
  }, // как трусливый роберт форд убил джесси джеймса
  {
    title: "Быстрый и мертвый",
    original: ["The Quick and the Dead"],
    release: "1995-02-10",
    publish: "2025-05-23T21:02:13",
    directors: ["Сэм Рэйми"],
    format: "фильм",
    liked: "like",
    screenshots: 39,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/2273/",
  }, // быстрый и мертвый
  {
    title: "Омерзительная восьмерка",
    original: ["The Hateful Eight", "The Hateful 8"],
    release: "2015-12-30",
    publish: "2025-05-17T10:17:07",
    directors: ["Квентин Тарантино"],
    operator: "Роберт Ричардсон",
    format: "фильм",
    liked: "like",
    screenshots: 54,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/819101/",
  }, // омерзительная восьмерка
  {
    title: "Поезд на Юму",
    original: ["3:10 to Yuma"],
    release: "2007-09-07",
    publish: "2025-05-11T12:04:39",
    directors: ["Джеймс Мэнголд"],
    format: "фильм",
    liked: "like",
    screenshots: 30,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/78240/",
  }, // поезд на юму
  {
    title: "Падение империи",
    original: ["Civil War"],
    release: "2024-04-12",
    publish: "2025-05-09T12:30:23",
    directors: ["Алекс Гарленд"],
    format: "фильм",
    liked: "like",
    screenshots: 21,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/4968810/",
  }, // падение империи
  {
    title: "Друзья навсегда",
    original: ["Our Friend"],
    release: "2019-09-06",
    publish: "2025-05-06T17:14:38",
    directors: ["Габриэла Каупертуэйт"],
    format: "фильм",
    liked: "like",
    screenshots: 38,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1231105/",
  }, // друзья навсегда
  {
    title: "Нарковоры",
    original: ["Dope Thief"],
    release: "2025-03-14",
    publish: "2025-05-04T17:02:47",
    format: "сериал",
    season: "1",
    isMiniSeries: false,
    liked: "dislike",
    screenshots: 42,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/5138508/",
  }, // нарковоры 1
  {
    title: "Железная хватка",
    original: ["True Grit"],
    release: "2010-12-22",
    publish: "2025-05-04T21:26:56",
    directors: ["Джоэл Коэн", "Итан Коэн"],
    operator: "Роджер Дикинс",
    format: "фильм",
    liked: "like",
    screenshots: 28,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/462553/",
  }, // железная хватка
  {
    title: "Стальная хватка",
    original: ["The Iron Claw"],
    release: "2023-12-22",
    publish: "2025-05-03T18:53:41",
    directors: ["Шон Дуркин"],
    format: "фильм",
    liked: "like",
    screenshots: 57,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5005446/",
  }, // стальная хватка
  {
    title: "Формула 1. Драйв выживания",
    original: ["Formula 1: Drive to Survive"],
    release: "2025-03-07",
    publish: "2025-05-03T15:36:46",
    format: "сериал",
    season: "7",
    isMiniSeries: false,
    liked: "like",
    screenshots: 45,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/1240162/",
  }, // формула 1. драйв выживания 7
  {
    title: "Жажда славы",
    original: ["Magazine Dreams"],
    release: "2023-01-20",
    publish: "2025-04-28T20:31:55",
    directors: ["Элайджа Байнум"],
    format: "фильм",
    liked: "dislike",
    screenshots: 39,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/4704816/",
  }, // жажда славы
  {
    title: "Чёрный чемодан – двойная игра",
    original: ["Black Bag"],
    release: "2025-03-14",
    publish: "2025-04-18T20:42:38",
    directors: ["Стивен Содерберг"],
    format: "фильм",
    liked: "like",
    screenshots: 48,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5449060/",
  }, // чёрный чемодан – двойная игра
  {
    title: "Фримонт. Американская мечта",
    original: ["Fremont"],
    release: "2023-10-10",
    publish: "2025-04-13T10:55:46",
    directors: ["Бабак Джалали"],
    format: "фильм",
    liked: "like",
    screenshots: 51,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5108082/",
  }, // фримонт
  {
    title: "Подземелья и драконы: Честь среди воров",
    original: ["Dungeons & Dragons: Honor Among Thieves"],
    release: "2023-03-31",
    publish: "2025-04-06T10:30:32",
    directors: ["Джон Фрэнсис Дейли", "Джонатан М. Голдштейн"],
    format: "фильм",
    liked: "like",
    screenshots: 20,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/762646/",
  }, // подземелья и драконы: честь среди воров
  {
    title: "Микки 17",
    original: ["Mickey 17"],
    release: "2025-03-07",
    publish: "2025-04-06T23:17:48",
    directors: ["Пон Джун-хо"],
    operator: "Дариус Хонджи",
    format: "фильм",
    liked: "dislike",
    screenshots: 42,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1320476/",
  }, // микки 17
  {
    title: "Любой ценой",
    original: ["Hell or High Water"],
    release: "2016-08-26",
    publish: "2025-04-06T19:22:27",
    directors: ["Дэвид Маккензи"],
    format: "фильм",
    liked: "like",
    screenshots: 33,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/726794/",
  }, // любой ценой
  {
    title: "Варвар",
    original: ["Barbarian"],
    release: "2022-09-09",
    publish: "2025-04-06T11:47:45",
    directors: ["Зак Креггер"],
    format: "фильм",
    liked: "like",
    screenshots: 30,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/4749790/",
  }, // варвар
  {
    title: "Частые побочные явления",
    original: ["Common Side Effects", "Обычные побочки"],
    release: "2025-02-02",
    publish: "2025-04-05T16:52:19",
    format: "сериал",
    season: "1",
    isMiniSeries: false,
    liked: "like",
    screenshots: 36,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/6990425/",
  }, // частые побочные явления 1
  {
    title: "Голый пистолет",
    original: ["The Naked Gun: From the Files of Police Squad!"],
    release: "1988-12-02",
    publish: "2025-04-05T09:24:15",
    directors: ["Дэвид Цукер"],
    format: "фильм",
    liked: "like",
    screenshots: 24,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/4067/",
  }, // голый пистолет (1988)
  {
    title: "Разделение",
    original: ["Severance"],
    release: "2025-01-17",
    publish: "2025-04-04T23:10:03",
    creators: ["Бен Стиллер", "Дэн Эриксон"],
    format: "сериал",
    season: "2",
    isMiniSeries: false,
    liked: "like",
    screenshots: 132,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/1343318/",
  }, // разделение 2
  {
    title: "Суперсемейка 2",
    original: ["Incredibles 2"],
    release: "2018-06-15",
    publish: "2025-03-30T20:46:55",
    directors: ["Брэд Бёрд"],
    format: "фильм",
    liked: "like",
    screenshots: 60,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/839650/",
  }, // суперсемейка 2
  {
    title: "Суперсемейка",
    original: ["The Incredibles"],
    release: "2004-11-05",
    publish: "2025-03-30T17:28:07",
    directors: ["Брэд Бёрд"],
    format: "фильм",
    liked: "like",
    screenshots: 33,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/38903/",
  }, // суперсемейка
  {
    title: "Мегамозг",
    original: ["Megamind"],
    release: "2010-11-05",
    publish: "2025-03-29T18:21:19",
    directors: ["Том МакГрат"],
    format: "фильм",
    liked: "like",
    screenshots: 30,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/405608/",
  }, // мегамозг
  {
    title: "Кровью и потом: Анаболики",
    original: ["Pain & Gain", "Анатолики"],
    release: "2013-04-26",
    publish: "2025-03-29T16:06:51",
    directors: ["Майкл Бэй"],
    format: "фильм",
    liked: "like",
    screenshots: 69,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/596227/",
  }, // кровью и потом: анаболики
  {
    title: "Жаркие летние ночи",
    original: ["Hot Summer Nights"],
    release: "2017-03-13",
    publish: "2025-03-29T22:05:00",
    directors: ["Элайджа Байнум"],
    format: "фильм",
    liked: "like",
    screenshots: 42,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/928993/",
  }, // жаркие летние ночи
  {
    title: "Проект Флорида",
    original: ["The Florida Project"],
    release: "2017-11-10",
    publish: "2025-03-28T15:50:29",
    directors: ["Шон Бэйкер"],
    format: "фильм",
    liked: "like",
    screenshots: 48,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/998317/",
  }, // проект флорида
  {
    title: "Маяк",
    original: ["The Lighthouse"],
    release: "2019-11-01",
    publish: "2025-03-26T17:22:10",
    directors: ["Роберт Эггерс"],
    format: "фильм",
    liked: "like",
    screenshots: 81,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1114927/",
  }, // маяк
  {
    title: "Лига справедливости Зака Снайдера: Черно-белая версия",
    original: ["Zack Snyder's Justice League: Justice Is Gray"],
    release: "2021-03-18",
    publish: "2025-03-26T11:03:58",
    directors: ["Зак Снайдер"],
    format: "фильм",
    liked: "dislike",
    screenshots: 126,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/4404112/",
  }, // лига справедливости зака снайдера
  {
    title: "Безумный Макс: Дорога ярости. Чёрно-белое издание",
    original: ["Mad Max: Fury Road Black And Chrome Edition"],
    release: "2016-12-01",
    publish: "2025-03-25T11:43:01",
    directors: ["Джордж Миллер"],
    format: "фильм",
    liked: "like",
    screenshots: 54,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/453406/",
  }, // безумный макс. чёрно-белое издание
  {
    title: "Синг-Синг",
    original: ["Sing Sing"],
    release: "2023-09-10",
    publish: "2025-03-21T20:44:06",
    directors: ["Грег Куидар"],
    format: "фильм",
    liked: "like",
    screenshots: 54,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5378058/",
  }, // синг-синг
  {
    title: "Отряд самоубийц: Миссия навылет",
    original: ["The Suicide Squad"],
    release: "2021-08-05",
    publish: "2025-03-21T18:13:46",
    directors: ["Джеймс Ганн"],
    format: "фильм",
    liked: "like",
    screenshots: 57,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1008477/",
  }, // отряд самоубийц: миссия навылет
  {
    title: "Книга джунглей",
    original: ["The Jungle Book"],
    release: "2016-04-15",
    publish: "2025-03-21T12:53:18",
    directors: ["Джон Фавро"],
    format: "фильм",
    liked: "like",
    screenshots: 36,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/779024/",
  }, // книга джунглей
  {
    title: "Присутствие",
    original: ["Presence"],
    release: "2024-01-19",
    publish: "2025-03-20T21:35:43",
    directors: ["Стивен Содерберг"],
    format: "фильм",
    liked: "like",
    screenshots: 21,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5445463/",
  }, // присутствие
  {
    title: "Логан: Нуар",
    original: ["Logan: Noir"],
    release: "2017-05-16",
    publish: "2025-03-20T15:44:28",
    directors: ["Джеймс Мэнголд"],
    format: "фильм",
    liked: "like",
    screenshots: 90,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/807682/",
  }, // логан: нуар
  {
    title: "Город воров",
    original: ["The Town"],
    release: "2010-09-17",
    publish: "2025-03-20T10:08:57",
    directors: ["Бен Аффлек"],
    operator: "Роберт Элсвит",
    format: "фильм",
    liked: "like",
    screenshots: 36,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/462732/",
  }, // город воров
  {
    title: "Непобедимый",
    original: ["Invincible"],
    release: "2025-02-06",
    publish: "2025-03-18T14:56:33",
    creators: ["Роберт Киркман"],
    format: "сериал",
    season: "3",
    isMiniSeries: false,
    liked: "like",
    screenshots: 60,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/1171895/",
  }, // непобедимый 3
  {
    title: "Бегущий по лезвию 2049",
    original: ["Blade Runner 2049"],
    release: "2017-10-06",
    publish: "2025-03-17T13:03:52",
    directors: ["Дени Вильнёв"],
    operator: "Роджер Дикинс",
    format: "фильм",
    liked: "like",
    screenshots: 78,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/589290/",
  }, // бегущий по лезвию 2049
  {
    title: "Враг",
    original: ["Enemy"],
    release: "2013-09-08",
    publish: "2025-03-13T19:01:45",
    directors: ["Дени Вильнёв"],
    format: "фильм",
    liked: "like",
    screenshots: 45,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/673910/",
  }, // враг
  {
    title: "Мстители: Эра Альтрона",
    original: ["Avengers: Age of Ultron"],
    release: "2015-05-01",
    publish: "2025-03-08T00:37:12",
    directors: ["Джосс Уидон"],
    format: "фильм",
    liked: "like",
    screenshots: 24,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/679830/",
  }, // мстители: эра альтрона
  {
    title: "Топ Ган: Мэверик",
    original: ["Top Gun: Maverick"],
    release: "2022-05-27",
    publish: "2025-03-02T17:10:20",
    directors: ["Джозеф Косински"],
    format: "фильм",
    liked: "like",
    screenshots: 51,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/572032/",
  }, // топ ган: мэверик
  {
    title: "Вавилон",
    original: ["Babel"],
    release: "2006-11-10",
    publish: "2025-03-02T11:52:15",
    directors: ["Алехандро Гонсалес Иньярриту"],
    format: "фильм",
    liked: "dislike",
    screenshots: 23,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/102125/",
  }, // вавилон (2006)
  {
    title: "Белфаст",
    original: ["Belfast"],
    release: "2021-11-12",
    publish: "2025-03-01T19:08:31",
    directors: ["Кеннет Брана"],
    format: "фильм",
    liked: "like",
    screenshots: 69,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1397888/",
  }, // белфаст
  {
    title: "Пожары",
    original: ["Incendies"],
    release: "2010-09-03",
    publish: "2025-03-01T23:24:09",
    directors: ["Дени Вильнёв"],
    format: "фильм",
    liked: "like",
    screenshots: 54,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/425400/",
  }, // пожары
  {
    title: "Мстители: Финал",
    original: ["Avengers: Endgame"],
    release: "2019-04-26",
    publish: "2025-03-01T02:36:12",
    directors: ["Джо Руссо", "Энтони Руссо"],
    format: "фильм",
    liked: "like",
    screenshots: 81,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/843650/",
  }, // мстители: финал
  {
    title: "Мстители: Война бесконечности",
    original: ["Avengers: Infinity War"],
    release: "2018-04-27",
    publish: "2025-02-28T22:25:17",
    directors: ["Джо Руссо", "Энтони Руссо"],
    format: "фильм",
    liked: "like",
    screenshots: 54,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/843649/",
  }, // мстители: война бесконечности
  {
    title: "Вершина богов",
    original: ["The Summit of the Gods", "Le sommet des dieux"],
    release: "2021-11-30",
    publish: "2025-02-28T18:40:01",
    directors: ["Патрик Имбер"],
    format: "фильм",
    liked: "like",
    screenshots: 69,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1090932/",
  }, // вершина богов
  {
    title: "Ущелье",
    original: ["The Gorge"],
    release: "2025-02-14",
    publish: "2025-02-22T17:06:54",
    directors: ["Скотт Дерриксон"],
    format: "фильм",
    liked: "dislike",
    screenshots: 45,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5098653/",
  }, // ущелье
  {
    title: "Трансформеры: Начало",
    original: ["Transformers One"],
    release: "2024-09-20",
    publish: "2025-02-22T13:07:42",
    directors: ["Джош Кули"],
    format: "фильм",
    liked: "like",
    screenshots: 15,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1229682/",
  }, // трансформеры: начало
  {
    title: "Бруталист",
    original: ["The Brutalist"],
    release: "2024-09-01",
    publish: "2025-02-21T21:52:44",
    directors: ["Брэйди Корбе"],
    format: "фильм",
    liked: "dislike",
    screenshots: 63,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1405331/",
  }, // бруталист
  {
    title: "Рома",
    original: ["Roma"],
    release: "2018-12-14",
    publish: "2025-02-17T07:35:43",
    directors: ["Альфонсо Куарон"],
    format: "фильм",
    liked: "like",
    screenshots: 42,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1008486/",
  }, // рома
  {
    title: "Неудержимый",
    original: ["Unstoppable", "Неукротимый"],
    release: "2024-09-06",
    publish: "2025-02-13T19:55:01",
    directors: ["Уильям Голденберг"],
    format: "фильм",
    liked: "like",
    screenshots: 42,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5455286/",
  }, // неудержимый
  {
    title: "Сорвиголова",
    original: ["Daredevil"],
    release: "2016-03-18",
    publish: "2025-02-02T20:47:46",
    creators: ["Дрю Годдард"],
    format: "сериал",
    season: "2",
    isMiniSeries: false,
    liked: "like",
    screenshots: 36,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/817509/",
  }, // сорвиголова 2
  {
    title: "Тренировочный день",
    original: ["Training Day"],
    release: "2001-10-05",
    publish: "2025-01-25T17:51:45",
    directors: ["Антуан Фукуа"],
    format: "фильм",
    liked: "like",
    screenshots: 42,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/863/",
  }, // тренировочный день
  {
    title: "Сокровище нации: Книга Тайн",
    original: ["National Treasure: Book of Secrets"],
    release: "2007-12-21",
    publish: "2025-01-26T11:21:58",
    directors: ["Джон Тёртлтауб"],
    format: "фильм",
    liked: "like",
    screenshots: 20,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/195408/",
  }, // сокровище нации
  {
    title: "Сокровище нации",
    original: ["National Treasure"],
    release: "2004-11-19",
    publish: "2025-01-25T14:11:06",
    directors: ["Джон Тёртлтауб"],
    format: "фильм",
    liked: "like",
    screenshots: 14,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/61333/",
  }, // сокровище нации
  {
    title: "Не пойман – не вор",
    original: ["Inside Man"],
    release: "2006-03-24",
    publish: "2025-01-19T13:04:41",
    directors: ["Спайк Ли"],
    format: "фильм",
    liked: "like",
    screenshots: 18,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/103785/",
  }, // не пойман не вор
  {
    title: "Лэндмен",
    original: ["Landman", "Землевладелец"],
    release: "2024-11-17",
    publish: "2025-01-19T18:02:12",
    creators: ["Тейлор Шеридан"],
    format: "сериал",
    season: "1",
    isMiniSeries: false,
    liked: "like",
    screenshots: 23,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/4909559/",
  }, // лэндмен 1
  {
    title: "Монстры-коммандос",
    original: ["Creature Commandos"],
    release: "2024-12-05",
    publish: "2025-01-12T10:10:47",
    creators: ["Джеймс Ганн"],
    format: "сериал",
    season: "1",
    isMiniSeries: false,
    liked: "like",
    screenshots: 33,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/5253831/",
  }, // монстры-коммандос 1
  {
    title: "Настоящая боль",
    original: ["A Real Pain"],
    release: "2024-11-15",
    publish: "2025-01-04T16:07:41",
    directors: ["Джесси Айзенберг"],
    format: "фильм",
    liked: "dislike",
    screenshots: 19,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5105866/",
  }, // настоящая боль
  {
    title: "Хоббит: Битва пяти воинств",
    original: ["The Hobbit: The Battle of the Five Armies"],
    release: "2014-12-17",
    publish: "2024-12-27T21:15:55",
    directors: ["Питер Джексон"],
    format: "фильм",
    liked: "like",
    screenshots: 14,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/694633/",
  }, // хоббит: битва пяти воинств (3)
  {
    title: "Хоббит: Пустошь Смауга",
    original: ["The Hobbit: The Desolation of Smaug"],
    release: "2013-12-13",
    publish: "2024-12-26T20:14:49",
    directors: ["Питер Джексон"],
    format: "фильм",
    liked: "like",
    screenshots: 23,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/408876/",
  }, // хоббит: пустошь смауга (2)
  {
    title: "Хоббит: Нежданное путешествие",
    original: ["The Hobbit: An Unexpected Journey"],
    release: "2012-12-14",
    publish: "2024-12-23T23:53:54",
    directors: ["Питер Джексон"],
    format: "фильм",
    liked: "like",
    screenshots: 36,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/278522/",
  }, // хоббит: нежданное путешествие (1)
  {
    title: "Идеальные дни",
    original: ["Perfect Days"],
    release: "2023-05-25",
    publish: "2024-12-15T12:37:54",
    directors: ["Вим Вендерс"],
    format: "фильм",
    liked: "like",
    screenshots: 45,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5283168/",
  }, // идеальные дни
  {
    title: "Его три дочери",
    original: ["His Three Daughters"],
    release: "2024-09-20",
    publish: "2024-12-15T19:10:39",
    directors: ["Азазель Джейкобс"],
    format: "фильм",
    liked: "like",
    screenshots: 33,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5368757/",
  }, // его три дочери
  {
    title: "Сёгун",
    original: ["Shogun", "Shôgun"],
    release: "2024-02-27",
    publish: "2024-12-14T18:27:57",
    format: "сериал",
    season: "1",
    isMiniSeries: false,
    liked: "dislike",
    screenshots: 23,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/749562/",
  }, // сёгун 1
  {
    title: "Аркейн",
    original: ["Arcane: League of Legends"],
    release: "2024-11-09",
    publish: "2024-11-23T20:20:28",
    format: "сериал",
    season: "2",
    isMiniSeries: false,
    liked: "like",
    screenshots: 35,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/4445150/",
  }, // aркейн 2
  {
    title: "Аркейн",
    original: ["Arcane: League of Legends"],
    release: "2021-11-06",
    publish: "2024-11-21T19:25:41",
    format: "сериал",
    season: "1",
    isMiniSeries: false,
    liked: "like",
    screenshots: 42,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/4445150/",
  }, // aркейн 1
  {
    title: "Пингвин",
    original: ["The Penguin"],
    release: "2024-09-19",
    publish: "2024-11-15T07:36:10",
    format: "сериал",
    isMiniSeries: true,
    liked: "like",
    screenshots: 36,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/4635062/",
  }, // пингвин
  {
    title: "Это всё Агата",
    original: ["Agatha All Along"],
    release: "2024-09-18",
    publish: "2024-11-03T12:12:58",
    format: "сериал",
    isMiniSeries: true,
    liked: "like",
    screenshots: 18,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/402955/",
  }, // это всё агата
  {
    title: "Дикий робот",
    original: ["The Wild Robot"],
    release: "2024-09-27",
    publish: "2024-10-27T13:57:31",
    directors: ["Крис Сандерс"],
    format: "фильм",
    liked: "like",
    screenshots: 21,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5457899/",
  }, // дикий робот
  {
    title: "Прослушка",
    original: ["The Wire"],
    release: "2008-01-06",
    publish: "2024-10-26T14:02:47",
    creators: ["Дэвид Саймон"],
    format: "сериал",
    season: "5",
    isMiniSeries: false,
    liked: "like",
    screenshots: 51,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/402955/",
  }, // прослушка 5
  {
    title: "Прослушка",
    original: ["The Wire"],
    release: "2006-09-10",
    publish: "2024-10-14T07:40:33",
    creators: ["Дэвид Саймон"],
    format: "сериал",
    season: "4",
    isMiniSeries: false,
    liked: "like",
    screenshots: 63,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/402955/",
  }, // прослушка 4
  {
    title: "The Vince Staples Show",
    original: ["The Vince Staples Show"],
    release: "2024-02-15",
    publish: "2024-09-10T20:49:32",
    creators: ["Йен Эдельман", "Винс Стэйплс", "Морис Уильямс"],
    format: "сериал",
    season: "1",
    isMiniSeries: false,
    liked: "like",
    screenshots: 30,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/5450042/",
  }, // vince staples show
  {
    title: "Подай знак",
    original: ["Blink Twice"],
    release: "2024-08-23",
    publish: "2024-10-01T12:33:13",
    directors: ["Зои Кравиц"],
    format: "фильм",
    liked: "like",
    screenshots: 35,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/4630624/",
  }, // подай знак
  {
    title: "Одинокие волки",
    original: ["Wolfs"],
    release: "2024-09-27",
    publish: "2024-10-01T19:40:30",
    directors: ["Джон Уоттс"],
    operator: "Ларкин Сайпл",
    format: "фильм",
    liked: "dislike",
    screenshots: 33,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/4825582/",
  }, // одинокие волки
  {
    title: "Гранд тур",
    original: ["The Grand Tour"],
    release: "2024-09-13",
    publish: "2024-09-30T15:32:27",
    format: "сериал",
    season: "6",
    isMiniSeries: false,
    liked: "like",
    screenshots: 21,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/982730/",
  }, // гранд тур 6
  {
    title: "Барри",
    original: ["Barry"],
    release: "2023-04-16",
    publish: "2024-09-08T21:07:28",
    creators: ["Алек Берг", "Билл Хейдер"],
    format: "сериал",
    season: "4",
    isMiniSeries: false,
    liked: "like",
    screenshots: 42,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/972587/",
  }, // барри 4
  {
    title: "Барри",
    original: ["Barry"],
    release: "2022-04-24",
    publish: "2024-09-08T14:14:03",
    creators: ["Алек Берг", "Билл Хейдер"],
    format: "сериал",
    season: "3",
    isMiniSeries: false,
    liked: "like",
    screenshots: 33,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/972587/",
  }, // барри 3
  {
    title: "Барри",
    original: ["Barry"],
    release: "2019-03-31",
    publish: "2024-09-08T09:04:35",
    creators: ["Алек Берг", "Билл Хейдер"],
    format: "сериал",
    season: "2",
    isMiniSeries: false,
    liked: "like",
    screenshots: 50,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/972587/",
  }, // барри 2
  {
    title: "Барри",
    original: ["Barry"],
    release: "2018-03-25",
    publish: "2024-09-07T12:44:42",
    creators: ["Алек Берг", "Билл Хейдер"],
    format: "сериал",
    season: "1",
    isMiniSeries: false,
    liked: "like",
    screenshots: 26,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/972587/",
  }, // барри 1
  {
    title: "Начальная школа «Эбботт»",
    original: ["Abbott Elementary"],
    release: "2024-02-27",
    publish: "2024-09-01T17:59:24",
    creators: ["Кинта Брансон"],
    format: "сериал",
    season: "3",
    isMiniSeries: false,
    liked: "like",
    screenshots: 33,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/4478603/",
  }, // начальная школа эбботт 3
  {
    title: "Медведь",
    original: ["The Bear"],
    release: "2024-06-26",
    publish: "2024-08-08T23:11:23",
    format: "сериал",
    season: "3",
    isMiniSeries: false,
    liked: "like",
    screenshots: 33,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/4481731/",
  }, // медведь 3
  {
    title: "Симпсоны",
    original: ["The Simpsons"],
    release: "2023-10-01",
    publish: "2024-08-23T21:31:41",
    creators: ["Мэтт Грейнинг"],
    format: "сериал",
    season: "35",
    isMiniSeries: false,
    liked: "like",
    screenshots: 41,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/77164/",
  }, // симпсоны 35
  {
    title: "Квартира",
    original: ["The Apartment"],
    release: "1960-06-29",
    publish: "2024-08-10T16:27:18",
    directors: ["Билли Уайлдер"],
    format: "фильм",
    liked: "like",
    screenshots: 18,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/404/",
  }, // квартира
  {
    title: "Великая ирония",
    original: ["Coup de chance"],
    release: "2023-09-04",
    publish: "2024-08-19T22:12:44",
    directors: ["Вуди Аллен"],
    format: "фильм",
    liked: "like",
    screenshots: 15,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/4541527/",
  }, // великая ирония
  {
    title: "Треугольник печали",
    original: ["Triangle of Sadness"],
    release: "2022-09-18",
    publish: "2024-08-18T19:27:21",
    directors: ["Рубен Эстлунд"],
    format: "фильм",
    liked: "like",
    screenshots: 39,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1348487/",
  }, // треугольник печали
  {
    title: "Мы",
    original: ["Us"],
    release: "2019-03-22",
    publish: "2024-08-18:22:00",
    directors: ["Джордан Пил"],
    format: "фильм",
    liked: "like",
    screenshots: 24,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1122138/",
  }, // мы
  {
    title: "О, где же ты, брат?",
    original: ["O Brother, Where Art Thou?"],
    release: "2000-05-13",
    publish: "2024-08-14T21:00:46",
    directors: ["Джоэл Коэн", "Итан Коэн"],
    operator: "Роджер Дикинс",
    format: "фильм",
    liked: "like",
    screenshots: 25,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/546/",
  }, // о где же ты брат
  {
    title: "Человек, которого не было",
    original: ["The Man Who Wasn't There"],
    release: "2001-11-16",
    publish: "2024-08-11T16:39:28",
    directors: ["Джоэл Коэн", "Итан Коэн"],
    operator: "Роджер Дикинс",
    format: "фильм",
    liked: "like",
    screenshots: 60,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/554/",
  }, // человек, которого не было
  {
    title: "Рики Стэники",
    original: ["Ricky Stanicky"],
    release: "2024-03-07",
    publish: "2024-08-11T22:39:13",
    directors: ["Питер Фаррелли"],
    format: "фильм",
    liked: "dislike",
    screenshots: 17,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/523111/",
  }, // рики стэники
  {
    title: "Невыносимая жестокость",
    original: ["Intolerable Cruelty"],
    release: "2003-10-10",
    publish: "2024-08-11T18:44:07",
    directors: ["Джоэл Коэн", "Итан Коэн"],
    operator: "Роджер Дикинс",
    format: "фильм",
    liked: "like",
    screenshots: 36,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/2886/",
  }, // невыносимая жестокость
  {
    title: "Зачинщики",
    original: ["The Instigators"],
    release: "2024-08-09",
    publish: "2024-08-11T14:16:12",
    directors: ["Даг Лайман"],
    format: "фильм",
    liked: "dislike",
    screenshots: 18,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5274244/",
  }, // зачинщики
  {
    title: "Бешеный бык",
    original: ["Raging Bull"],
    release: "1980-12-19",
    publish: "2024-08-11T11:21:39",
    directors: ["Мартин Скорсезе"],
    format: "фильм",
    liked: "dislike",
    screenshots: 24,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/374/",
  }, // бешеный бык
  {
    title: "Подстава",
    original: ["Set It Up"],
    release: "2018-06-15",
    publish: "2024-08-10T13:22:24",
    directors: ["Клер Скэнлон"],
    format: "фильм",
    liked: "like",
    screenshots: 22,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/976520/",
  }, // подстава
  {
    title: "Касабланка",
    original: ["Casablanca"],
    release: "1942-11-26",
    publish: "2024-08-10T19:57:38",
    directors: ["Майкл Кёртиц"],
    format: "фильм",
    liked: "like",
    screenshots: 26,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/330/",
  }, // касабланка
  {
    title: "Тёмная материя",
    original: ["Dark Matter"],
    release: "2024-05-07",
    publish: "2024-08-08T07:32:28",
    format: "сериал",
    season: "1",
    isMiniSeries: false,
    liked: "like",
    screenshots: 39,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/5024113/",
  }, // темная материя 1
  {
    title: "Пацаны",
    original: ["The Boys"],
    release: "2024-06-13",
    publish: "2024-08-02T00:36:47",
    creators: ["Эрик Крипке"],
    format: "сериал",
    season: "4",
    isMiniSeries: false,
    liked: "like",
    screenshots: 36,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/460586/",
  }, // пацаны 4
  {
    title: "Формула 1. Драйв выживания",
    original: ["Formula 1: Drive to Survive"],
    release: "2024-02-23",
    publish: "2024-07-21T23:42:09",
    format: "сериал",
    season: "6",
    isMiniSeries: false,
    liked: "like",
    screenshots: 29,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/1240162/",
  }, // формула 1. драйв выживания 6
  {
    title: "Формула 1. Драйв выживания",
    original: ["Formula 1: Drive to Survive"],
    release: "2023-02-24",
    publish: "2024-07-14T11:36:49",
    format: "сериал",
    season: "5",
    isMiniSeries: false,
    liked: "like",
    screenshots: 27,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/1240162/",
  }, // формула 1. драйв выживания 5
  {
    title: "Я не киллер",
    original: ["Hit Man"],
    release: "2023-09-05",
    publish: "2024-07-13T21:21:09",
    directors: ["Ричард Линклейтер"],
    format: "фильм",
    liked: "like",
    screenshots: 39,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5051126/",
  }, // я не киллер
  {
    title: "Гарфилд",
    original: ["The Garfield Movie"],
    release: "2024-05-24",
    publish: "2024-07-13T19:14:25",
    directors: ["Марк Диндал"],
    format: "фильм",
    liked: "dislike",
    screenshots: 24,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1044220/",
  }, // гарфилд
  {
    title: "Претенденты",
    original: ["Challengers"],
    release: "2024-04-26",
    publish: "2024-06-15T18:15:25",
    directors: ["Лука Гуаданьино"],
    format: "фильм",
    liked: "like",
    screenshots: 69,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/4860116/",
  }, // претенденты
  {
    title: "Каскадёры",
    original: ["The Fall Guy"],
    release: "2024-05-03",
    publish: "2024-06-15T22:17:52",
    directors: ["Дэвид Литч"],
    format: "фильм",
    liked: "dislike",
    screenshots: 15,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/535243/",
  }, // каскадеры
  {
    title: "Формула 1. Драйв выживания",
    original: ["Formula 1: Drive to Survive"],
    release: "2022-03-11",
    publish: "2024-06-07T07:34:54",
    format: "сериал",
    season: "4",
    isMiniSeries: false,
    liked: "like",
    screenshots: 21,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/1240162/",
  }, // формула 1. драйв выживания 4
  {
    title: "Формула 1. Драйв выживания",
    original: ["Formula 1: Drive to Survive"],
    release: "2021-03-19",
    publish: "2024-05-30T07:27:24",
    format: "сериал",
    season: "3",
    isMiniSeries: false,
    liked: "like",
    screenshots: 12,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/1240162/",
  }, // формула 1. драйв выживания 3
  {
    title: "Люди Икс ’97",
    original: ["X-Men '97"],
    release: "2024-03-20",
    publish: "2024-05-19T15:51:51",
    format: "сериал",
    season: "1",
    isMiniSeries: false,
    liked: "like",
    screenshots: 39,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/4711940/",
  }, // люди икс ’97 1
  {
    title: "Талантливый мистер Рипли",
    original: ["The Talented Mr. Ripley"],
    release: "1999-12-25",
    publish: "2024-05-13T19:56:49",
    directors: ["Энтони Мингелла"],
    format: "фильм",
    liked: "dislike",
    screenshots: 30,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5558/",
  }, // талантливый мистер рипли
  {
    title: "Дюна: Часть вторая",
    original: ["Dune: Part Two"],
    release: "2024-03-01",
    publish: "2024-05-11T09:11:12",
    directors: ["Дени Вильнёв"],
    operator: "Грег Фрейзер",
    format: "фильм",
    liked: "like",
    screenshots: 78,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/4540126/",
  }, // дюна 2
  {
    title: "Рипли",
    original: ["Ripley"],
    release: "2024-04-04",
    publish: "2024-05-05T23:59:35",
    directors: ["Стивен Зеллиан"],
    operator: "Роберт Элсвит",
    format: "сериал",
    isMiniSeries: true,
    liked: "like",
    screenshots: 309,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/1311083/",
  }, // рипли
  {
    title: "Полиция Токио",
    original: ["Tokyo Vice"],
    release: "2024-02-08",
    publish: "2024-05-04T00:03:04",
    format: "сериал",
    season: "2",
    isMiniSeries: false,
    liked: "like",
    screenshots: 27,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/762194/",
  }, // полиция токио 2
  {
    title: "Программисты",
    original: ["Devs"],
    release: "2020-03-05",
    publish: "2024-04-30T12:54:11",
    creators: ["Алекс Гарленд"],
    format: "сериал",
    isMiniSeries: true,
    liked: "dislike",
    screenshots: 51,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/1137249/",
  }, // программисты
  {
    title: "Fallout",
    original: ["Fallout"],
    release: "2024-04-10",
    publish: "2024-04-29T15:33:43",
    creators: ["Джонатан Нолан", "Лиза Джой"],
    format: "сериал",
    season: "1",
    isMiniSeries: false,
    liked: "like",
    screenshots: 27,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/1394131/",
  }, // fallout 1
  {
    title: "Непобедимый",
    original: ["Invincible"],
    release: "2023-11-03",
    publish: "2024-04-16T20:44:08",
    creators: ["Роберт Киркман"],
    format: "сериал",
    season: "2",
    isMiniSeries: false,
    liked: "like",
    screenshots: 45,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/1171895/",
  }, // непобедимый 2
  {
    title: "Третий лишний",
    original: ["Ted"],
    release: "2024-01-11",
    publish: "2024-03-28T20:04:19",
    creators: ["Сет Макфарлейн"],
    format: "сериал",
    season: "1",
    isMiniSeries: false,
    liked: "like",
    screenshots: 25,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/4475348/",
  }, // третий лишний 1
  {
    title: "Кэрол и конец света",
    original: ["Carol & The End of the World"],
    release: "2023-12-15",
    publish: "2024-03-24T13:20:18",
    format: "сериал",
    isMiniSeries: true,
    liked: "dislike",
    screenshots: 36,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/5405539/",
  }, // кэрол и конец света
  {
    title: "Мечты робота",
    original: ["Robot Dreams"],
    release: "2023-05-20",
    publish: "2024-03-23T12:16:38",
    directors: ["Пабло Берхер"],
    format: "фильм",
    liked: "dislike",
    screenshots: 28,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5321227/",
  }, // мечты робота
  {
    title: "Эрнест и Селестина: Приключения мышки и медведя",
    original: ["Ernest & Celestine", "Ernest et Célestine"],
    release: "2012-05-23",
    publish: "2024-03-20T20:51:18",
    directors: ["Стефани Обье", "Венсан Патар", "Бенжамин Реннер"],
    format: "фильм",
    liked: "like",
    screenshots: 22,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/592260/",
  }, // эрнест и селестина
  {
    title: "Тысяча и один",
    original: ["A Thousand and One"],
    release: "2023-03-31",
    publish: "2024-03-18T21:09:25",
    directors: ["А.В. Рокуэлл"],
    format: "фильм",
    liked: "like",
    screenshots: 51,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1431429/",
  }, // тысяча и один
  {
    title: "Рами",
    original: ["Ramy"],
    release: "2022-09-30",
    publish: "2024-03-13T19:07:29",
    creators: ["Рами Юссеф"],
    format: "сериал",
    season: "3",
    isMiniSeries: false,
    liked: "like",
    screenshots: 27,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/1108755/",
  }, // рами 3
  {
    title: "Дело Коллини",
    original: ["The Collini Case", "Der Fall Collini"],
    release: "2019-04-18",
    publish: "2024-03-04T21:24:43",
    directors: ["Марко Кройцпайнтнер"],
    format: "фильм",
    liked: "like",
    screenshots: 12,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1179501/",
  }, // дело коллини
  {
    title: "Большой злой лис и другие сказки",
    original: [
      "The Big Bad Fox and Other Tales...",
      "Le grand méchant renard et autres contes...",
    ],
    release: "2017-06-21",
    publish: "2024-03-04T07:53:50",
    directors: ["Патрик Имбер", "Бенжамин Реннер"],
    format: "фильм",
    liked: "like",
    screenshots: 45,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1047719/",
  }, // большой злой лис и другие сказки
  {
    title: "Бедные-несчастные",
    original: ["Poor Things"],
    release: "2023-09-01",
    publish: "2024-03-03T13:00:28",
    directors: ["Йоргос Лантимос"],
    format: "фильм",
    liked: "like",
    screenshots: 39,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/4396438/",
  }, // бедные несчастные
  {
    title: "Американское чтиво",
    original: ["American Fiction"],
    release: "2023-09-08",
    publish: "2024-03-03T15:36:45",
    directors: ["Корд Джефферсон"],
    format: "фильм",
    liked: "like",
    screenshots: 21,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5212291/",
  }, // американское чтиво
  {
    title: "Сорвиголова",
    original: ["Daredevil"],
    release: "2015-04-10",
    publish: "2024-03-02T09:55:37",
    creators: ["Дрю Годдард"],
    format: "сериал",
    season: "1",
    isMiniSeries: false,
    liked: "like",
    screenshots: 33,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/817509/",
  }, // сорвиголова 1
  {
    title: "Миграция",
    original: ["Migration"],
    release: "2023-12-22",
    publish: "2024-02-25T21:27:26",
    directors: ["Бенжамин Реннер", "Гейло Хомси"],
    format: "фильм",
    liked: "like",
    screenshots: 18,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/4878248/",
  }, // миграция
  {
    title: "Гранд тур",
    original: ["The Grand Tour"],
    release: "2022-09-16",
    publish: "2024-02-25T13:25:24",
    format: "сериал",
    season: "5",
    isMiniSeries: false,
    liked: "like",
    screenshots: 30,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/982730/",
  }, // гранд тур 5
  {
    title: "Мистер и миссис Смит",
    original: ["Mr. & Mrs. Smith"],
    release: "2024-02-02",
    publish: "2024-02-17T14:46:09",
    creators: ["Дональд Гловер", "Франческа Слоун"],
    format: "сериал",
    season: "1",
    isMiniSeries: false,
    liked: "like",
    screenshots: 102,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/4363942/",
  }, // мистер и миссис смит 1
  {
    title: "Прослушка",
    original: ["The Wire"],
    release: "2004-09-19",
    publish: "2024-02-13T23:03:28",
    creators: ["Дэвид Саймон"],
    format: "сериал",
    season: "3",
    isMiniSeries: false,
    liked: "like",
    screenshots: 75,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/402955/",
  }, // прослушка 3
  {
    title: "Орион и Тьма",
    original: ["Orion and the Dark"],
    release: "2024-02-02",
    publish: "2024-02-06T07:19:09",
    directors: ["Шон Чэрмэтц"],
    format: "фильм",
    liked: "like",
    screenshots: 27,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5326241/",
  }, // орион и тьма
  {
    title: "Прослушка",
    original: ["The Wire"],
    release: "2003-06-01",
    publish: "2024-02-04T14:10:18",
    creators: ["Дэвид Саймон"],
    format: "сериал",
    season: "2",
    isMiniSeries: false,
    liked: "like",
    screenshots: 75,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/402955/",
  }, // прослушка 2
  {
    title: "Фарго",
    original: ["Fargo"],
    release: "2023-11-21",
    publish: "2024-01-28T10:18:59",
    creators: ["Ноа Хоули"],
    format: "сериал",
    season: "5",
    isMiniSeries: false,
    liked: "like",
    screenshots: 30,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/767379/",
  }, // фарго 5
  {
    title: "Следующий гол – победный",
    original: ["Next Goal Wins"],
    release: "2023-11-17",
    publish: "2024-01-28T13:10:39",
    directors: ["Тайка Вайтити"],
    format: "фильм",
    liked: "dislike",
    screenshots: 27,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1318952/",
  }, // следующий гол победный
  {
    title: "Прослушка",
    original: ["The Wire"],
    release: "2002-06-02",
    publish: "2024-01-25T08:05:00",
    creators: ["Дэвид Саймон"],
    format: "сериал",
    season: "1",
    isMiniSeries: false,
    liked: "like",
    screenshots: 108,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/402955/",
  }, // прослушка 1
  {
    title: "Время побеждать: Расцвет династии Лейкерс",
    original: ["Winning Time: The Rise of the Lakers Dynasty"],
    release: "2023-08-06",
    publish: "2024-01-17T21:12:29",
    format: "сериал",
    season: "2",
    isMiniSeries: false,
    liked: "like",
    screenshots: 45,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/1272097/",
  }, // расцвет династии лейкерс 2
  {
    title: "Смерть на похоронах",
    original: ["Death at a Funeral"],
    release: "2010-04-16",
    publish: "2024-01-13T22:50:52",
    directors: ["Нил Лабут"],
    format: "фильм",
    liked: "like",
    screenshots: 33,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/450725/",
  }, // смерть на похоронах
  {
    title: "Начальная школа «Эбботт»",
    original: ["Abbott Elementary"],
    release: "2022-09-21",
    publish: "2024-01-13T13:58:58",
    creators: ["Кинта Брансон"],
    format: "сериал",
    season: "2",
    isMiniSeries: false,
    liked: "like",
    screenshots: 42,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/4478603/",
  }, // начальная школа эбботт 2
  {
    title: "Начальная школа «Эбботт»",
    original: ["Abbott Elementary"],
    release: "2021-12-07",
    publish: "2024-01-08T16:22:51",
    creators: ["Кинта Брансон"],
    format: "сериал",
    season: "1",
    isMiniSeries: false,
    liked: "like",
    screenshots: 24,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/4478603/",
  }, // начальная школа эбботт 1
  {
    title: "Пережить Рождество",
    original: ["Surviving Christmas"],
    release: "2004-10-22",
    publish: "2023-12-30T17:52:33",
    directors: ["Майк Митчелл"],
    format: "фильм",
    liked: "like",
    screenshots: 18,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/20105/",
  }, // пережить рождество
  {
    title: "Рик и Морти",
    original: ["Rick and Morty"],
    release: "2023-10-15",
    publish: "2023-12-28T07:54:25",
    creators: ["Дэн Хармон", "Джастин Ройланд"],
    format: "сериал",
    season: "7",
    isMiniSeries: false,
    liked: "like",
    screenshots: 33,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/685246/",
  }, // рик и морти 7
  {
    title: "Кунг-фу Панда 3",
    original: ["Kung Fu Panda 3"],
    release: "2016-01-29",
    publish: "2023-12-26T21:49:36",
    directors: ["Алессандро Карлони", "Дженнифер Ю Нельсон"],
    format: "фильм",
    liked: "like",
    screenshots: 18,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/692865/",
  }, // кунг-фу панда 3
  {
    title: "Ну что, приехали: Ремонт",
    original: ["Are We Done Yet?"],
    release: "2007-04-04",
    publish: "2023-12-24T15:48:47",
    directors: ["Стив Карр"],
    format: "фильм",
    liked: "dislike",
    screenshots: 15,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/102247/",
  }, // ну что, приехали: ремонт
  {
    title: "Кунг-фу Панда 2",
    original: ["Kung Fu Panda 2"],
    release: "2011-05-26",
    publish: "2023-12-21T07:37:37",
    directors: ["Дженнифер Ю Нельсон"],
    format: "фильм",
    liked: "like",
    screenshots: 20,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/427878/",
  }, // кунг-фу панда 2
  {
    title: "Кунг-фу Панда",
    original: ["Kung Fu Panda"],
    release: "2008-06-06",
    publish: "2023-12-18T20:26:16",
    directors: ["Марк Осборн", "Джон Стивенсон"],
    format: "фильм",
    liked: "like",
    screenshots: 33,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/103734/",
  }, // кунг-фу панда
  {
    title: "Прошлые жизни",
    original: ["Past Lives"],
    release: "2023-06-23",
    publish: "2023-12-17T14:35:59",
    directors: ["Селин Сон"],
    format: "фильм",
    liked: "like",
    screenshots: 30,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1346482/",
  }, // прошлые жизни
  {
    title: "Оставленные",
    original: ["The Holdovers"],
    release: "2023-11-10",
    publish: "2023-12-17T09:38:30",
    directors: ["Александр Пэйн"],
    format: "фильм",
    liked: "like",
    screenshots: 21,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/4499386/",
  }, // оставленные
  {
    title: "Оставь мир позади",
    original: ["Leave the World Behind"],
    release: "2023-12-08",
    publish: "2023-12-13T19:48:21",
    directors: ["Сэм Эсмейл"],
    format: "фильм",
    liked: "like",
    screenshots: 33,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/4511543/",
  }, // оставь мир позади
  {
    title: "Май декабрь",
    original: ["May December"],
    release: "2023-12-01",
    publish: "2023-12-10T22:29:33",
    directors: ["Тодд Хейнс"],
    format: "фильм",
    liked: "like",
    screenshots: 23,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/4477074/",
  }, // май декабрь
  {
    title: "Голубоглазый самурай",
    original: ["Blue Eye Samurai"],
    release: "2023-11-03",
    publish: "2023-12-09T18:47:04",
    format: "сериал",
    season: "1",
    isMiniSeries: false,
    liked: "like",
    screenshots: 33,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/4992678/",
  }, // голубоглазый самурай 1
  {
    title: "Сообщество",
    original: ["Community"],
    release: "2015-03-17",
    publish: "2023-12-03T23:42:44",
    creators: ["Дэн Хармон"],
    format: "сериал",
    season: "6",
    isMiniSeries: false,
    liked: "like",
    screenshots: 12,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/471825/",
  }, // сообщетсво 6
  {
    title: "Уроки химии",
    original: ["Lessons in Chemistry"],
    release: "2023-10-13",
    publish: "2023-11-27T21:12:16",
    creators: ["Алекс Гарленд"],
    format: "сериал",
    isMiniSeries: true,
    liked: "like",
    screenshots: 15,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/4367624/",
  }, // уроки химии
  {
    title: "Лео",
    original: ["Leo"],
    release: "2023-11-21",
    publish: "2023-11-27T07:46:14",
    directors: ["Роберт Марианетти", "Роберт Шмигель", "Дэвид Уочтенхейм"],
    format: "фильм",
    liked: "dislike",
    screenshots: 15,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1346564/",
  }, // лео
  {
    title: "Быть присяжным",
    original: ["Jury Duty"],
    release: "2023-04-07",
    publish: "2023-11-26T17:46:17",
    format: "сериал",
    season: "1",
    isMiniSeries: false,
    liked: "like",
    screenshots: 18,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/5106451/",
  }, // быть присяжным
  {
    title: "Поколение «Ви»",
    original: ["Gen V"],
    release: "2023-09-23",
    publish: "2023-11-19T12:51:34",
    creators: ["Эрик Крипке", "Эван Голдберг", "Крэйг Розенберг", "Сет Роген"],
    format: "сериал",
    season: "1",
    isMiniSeries: false,
    liked: "like",
    screenshots: 18,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/1431133/",
  }, // поколение «ви» 1
  {
    title: "Оппенгеймер",
    original: ["Oppenheimer"],
    release: "2023-07-21",
    publish: "2023-11-18T13:23:09",
    directors: ["Кристофер Нолан"],
    operator: "Хойте Ван Хойтема",
    format: "фильм",
    liked: "dislike",
    screenshots: 27,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/4664634/",
  }, // оппенгеймер
  {
    title: "Создатель",
    original: ["The Creator"],
    release: "2023-09-29",
    publish: "2023-11-15T22:29:10",
    directors: ["Гарет Эдвардс"],
    operator: "Грег Фрейзер",
    format: "фильм",
    liked: "dislike",
    screenshots: 14,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/4499408/",
  }, // создатель
  {
    title: "Локи",
    original: ["Loki"],
    release: "2023-10-05",
    publish: "2023-11-15T07:18:25",
    creators: ["Майкл Уолдрон"],
    format: "сериал",
    season: "2",
    isMiniSeries: false,
    liked: "like",
    screenshots: 30,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/1203039/",
  }, // локи 2
  {
    title: "Убийца",
    original: ["The Killer"],
    release: "2023-11-10",
    publish: "2023-11-11T18:32:07",
    directors: ["Дэвид Финчер"],
    format: "фильм",
    liked: "like",
    screenshots: 21,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/462656/",
  }, // убийца
  {
    title: "Скрежет металла",
    original: ["Twisted Metal"],
    release: "2023-07-27",
    publish: "2023-11-06T16:10:21",
    creators: ["Майкл Уолдрон"],
    format: "сериал",
    season: "1",
    isMiniSeries: false,
    liked: "dislike",
    screenshots: 17,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/4397762/",
  }, // скрежет металла 1
  {
    title: "Атлантида: Затерянный мир",
    original: ["Atlantis: The Lost Empire"],
    release: "2001-06-15",
    publish: "2023-10-31T07:18:06",
    directors: ["Гари Труздейл", "Кирк Уайз"],
    format: "фильм",
    liked: "like",
    screenshots: 14,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/597/",
  }, // атлантида: затерянный мир
  {
    title: "Неудачницы",
    original: ["Bottoms"],
    release: "2023-03-11",
    publish: "2023-10-17T07:31:53",
    directors: ["Эмма Селигман"],
    format: "фильм",
    liked: "like",
    screenshots: 14,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/4994465/",
  }, // неудачницы
  {
    title: "Футурама",
    original: ["Futurama"],
    release: "2023-07-24",
    publish: "2023-10-15T18:26:42",
    creators: ["Мэтт Грейнинг", "Дэвид И. Коэн"],
    format: "сериал",
    season: "11",
    isMiniSeries: false,
    liked: "like",
    screenshots: 24,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/79920/",
  }, // футурама 11
  {
    title: "Псы резервации",
    original: ["Reservation Dogs"],
    release: "2023-08-02",
    publish: "2023-10-12T20:08:54",
    creators: ["Тайка Вайтити", "Стерлин Харджо"],
    format: "сериал",
    season: "3",
    isMiniSeries: false,
    liked: "like",
    screenshots: 30,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/4296469/",
  }, // псы резервации 3
  {
    title: "Миссия невыполнима: Смертельная расплата",
    original: ["Mission: Impossible - Dead Reckoning", "Part One"],
    release: "2023-07-12",
    publish: "2023-10-12T00:11:18",
    directors: ["Кристофер Маккуорри"],
    format: "фильм",
    liked: "like",
    screenshots: 17,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1229684/",
  }, // миссия невыполнима: смертельная расплата (7)
  {
    title: "Харли Квинн",
    original: ["Harley Quinn"],
    release: "2023-07-27",
    publish: "2023-10-07T22:51:54",
    format: "сериал",
    season: "1-4",
    releaseDates: ["2019-11-29", "2020-04-03", "2022-07-28", "2023-07-27"],
    isMiniSeries: false,
    liked: "like",
    screenshots: 42,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/1112514/",
  }, // харли квинн 1-4
  {
    title: "Сексуальное просвещение",
    original: ["Sex Education", "Половое воспитание"],
    release: "2023-09-21",
    publish: "2023-10-03T20:57:04",
    format: "сериал",
    season: "4",
    isMiniSeries: false,
    liked: "like",
    screenshots: 23,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/1147693/",
  }, // сексуальное просвещение 4
  {
    title: "Пароль «Рыба-меч»",
    original: ["Swordfish"],
    release: "2001-06-08",
    publish: "2023-09-30T15:43:56",
    directors: ["Доминик Сена"],
    format: "фильм",
    liked: "dislike",
    screenshots: 21,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/849/",
  }, // пароль «рыба-меч»
  {
    title: "Гран туризмо",
    original: ["Gran Turismo"],
    release: "2023-08-25",
    publish: "2023-09-30T12:25:38",
    directors: ["Нил Бломкамп"],
    format: "фильм",
    liked: "like",
    screenshots: 17,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1044002/",
  }, // гран туризмо
  {
    title: "Чудесная история Генри Шугара",
    original: ["The Wonderful Story of Henry Sugar"],
    release: "2023-09-27",
    publish: "2023-09-29T21:49:37",
    directors: ["Уэс Андерсон"],
    format: "фильм",
    liked: "dislike",
    screenshots: 22,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/4830353/",
  }, // чудесная история генри шугара
  {
    title: "Синий Жук",
    original: ["Blue Beetle"],
    release: "2023-08-18",
    publish: "2023-09-29T20:21:45",
    directors: ["Анхель Мануэль Сото"],
    format: "фильм",
    liked: "dislike",
    screenshots: 17,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1219153/",
  }, // синий жук
  {
    title: "Фестиваль Рифкина",
    original: ["Rifkin's Festival"],
    release: "2020-10-02",
    publish: "2023-09-19T11:10:56",
    directors: ["Вуди Аллен"],
    format: "фильм",
    liked: "dislike",
    screenshots: 28,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1169702/",
  }, // фестиваль рифкина
  {
    title: "Взрослые",
    original: ["The Adults"],
    release: "2023-09-05",
    publish: "2023-09-18T09:10:43",
    directors: ["Дастин Гай Дефа"],
    format: "фильм",
    liked: "dislike",
    screenshots: 22,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/5256888/",
  }, // взрослые
  {
    title: "Люди Икс: Последняя битва",
    original: ["X-Men: The Last Stand"],
    release: "2006-05-26",
    publish: "2023-09-15T21:04:16",
    directors: ["Бретт Рэтнер"],
    format: "фильм",
    liked: "like",
    screenshots: 34,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/61361/",
  }, // люди икс 3
  {
    title: "Люди Икс 2",
    original: ["X2"],
    release: "2003-05-02",
    publish: "2023-09-15T18:15:23",
    directors: ["Брайан Сингер"],
    format: "фильм",
    liked: "like",
    screenshots: 22,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/298/",
  }, // люди икс 2
  {
    title: "Люди Икс",
    original: ["X-Men"],
    release: "2000-07-14",
    publish: "2023-09-13T21:11:15",
    directors: ["Брайан Сингер"],
    format: "фильм",
    liked: "like",
    screenshots: 26,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/886/",
  }, // люди икс
  {
    title: "Время Армагеддона",
    original: ["Armageddon Time"],
    release: "2022-11-04",
    publish: "2023-09-11T07:47:02",
    directors: ["Джеймс Грэй"],
    operator: "Дариус Хонджи",
    format: "фильм",
    liked: "dislike",
    screenshots: 21,
    kinopoiskUrl: "https://www.kinopoisk.ru/film/1388894/",
  }, // время армагеддона
  {
    title: "Медведь",
    original: ["The Bear"],
    release: "2023-06-22",
    publish: "2023-08-05T22:53:38",
    format: "сериал",
    season: "2",
    isMiniSeries: false,
    liked: "like",
    screenshots: 63,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/4481731/",
  }, // медведь 2

  {
    title: "Разделение",
    original: ["Severance"],
    release: "2022-02-18",
    publish: "2022-04-27T21:06:25",
    creators: ["Бен Стиллер", "Дэн Эриксон"],
    format: "сериал",
    season: "1",
    isMiniSeries: false,
    liked: "like",
    screenshots: 45,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/1343318/",
  }, // разделение 1
  {
    title: "Непобедимый",
    original: ["Invincible"],
    release: "2021-03-26",
    publish: "2021-05-09T22:03:03",
    creators: ["Роберт Киркман"],
    format: "сериал",
    season: "1",
    isMiniSeries: false,
    liked: "like",
    screenshots: 30,
    kinopoiskUrl: "https://www.kinopoisk.ru/series/1171895/",
  }, // непобедимый 1
]; // ГЛАВНЫЙ МАССИВ
